set_property -dict {PACKAGE_PIN AA14 IOSTANDARD LVCMOS33} [get_ports {GEPHY_RD[3]}]
set_property -dict {PACKAGE_PIN Y13 IOSTANDARD LVCMOS33} [get_ports {GEPHY_RD[2]}]
set_property -dict {PACKAGE_PIN AB15 IOSTANDARD LVCMOS33} [get_ports {GEPHY_RD[1]}]
set_property -dict {PACKAGE_PIN AA15 IOSTANDARD LVCMOS33} [get_ports {GEPHY_RD[0]}]
set_property -dict {PACKAGE_PIN AB17 IOSTANDARD LVCMOS33} [get_ports {GEPHY_TD[3]}]
set_property -dict {PACKAGE_PIN AB16 IOSTANDARD LVCMOS33} [get_ports {GEPHY_TD[2]}]
set_property -dict {PACKAGE_PIN AA16 IOSTANDARD LVCMOS33} [get_ports {GEPHY_TD[1]}]
set_property -dict {PACKAGE_PIN Y16 IOSTANDARD LVCMOS33} [get_ports {GEPHY_TD[0]}]
set_property -dict {PACKAGE_PIN W11 IOSTANDARD LVCMOS33} [get_ports GEPHY_MAC_CLK]
set_property -dict {PACKAGE_PIN T16 IOSTANDARD LVCMOS33} [get_ports GEPHY_PMEB]
set_property -dict {PACKAGE_PIN Y11 IOSTANDARD LVCMOS33} [get_ports GEPHY_RCK]
set_property -dict {PACKAGE_PIN U16 IOSTANDARD LVCMOS33} [get_ports GEPHY_RST_N]
set_property -dict {PACKAGE_PIN AA9 IOSTANDARD LVCMOS33} [get_ports GEPHY_RXDV_ER]
set_property -dict {PACKAGE_PIN AB13 IOSTANDARD LVCMOS33} [get_ports GEPHY_TCK]
set_property -dict {PACKAGE_PIN AA13 IOSTANDARD LVCMOS33} [get_ports GEPHY_TXEN_ER]
set_property -dict {PACKAGE_PIN E21 IOSTANDARD LVCMOS33} [get_ports LED0]
set_property -dict {PACKAGE_PIN D21 IOSTANDARD LVCMOS33} [get_ports LED1]
set_property -dict {PACKAGE_PIN G22 IOSTANDARD LVCMOS33} [get_ports LED2]
set_property -dict {PACKAGE_PIN H4 IOSTANDARD LVDS_25} [get_ports sys_clk_p]
set_property -dict {PACKAGE_PIN G4 IOSTANDARD LVDS_25} [get_ports sys_clk_n]
set_property -dict {PACKAGE_PIN D19 IOSTANDARD LVCMOS33} [get_ports sys_rst_n]

set_property -dict {PACKAGE_PIN C14 IOSTANDARD LVCMOS33} [get_ports GPIO00]
set_property -dict {PACKAGE_PIN C15 IOSTANDARD LVCMOS33} [get_ports GPIO01]
set_property -dict {PACKAGE_PIN D14 IOSTANDARD LVCMOS33} [get_ports GPIO02]
set_property -dict {PACKAGE_PIN D15 IOSTANDARD LVCMOS33} [get_ports GPIO03]
set_property -dict {PACKAGE_PIN B15 IOSTANDARD LVCMOS33} [get_ports GPIO04]
set_property -dict {PACKAGE_PIN B16 IOSTANDARD LVCMOS33} [get_ports GPIO05]
set_property -dict {PACKAGE_PIN C13 IOSTANDARD LVCMOS33} [get_ports GPIO06]
set_property -dict {PACKAGE_PIN B13 IOSTANDARD LVCMOS33} [get_ports GPIO07]
set_property -dict {PACKAGE_PIN A15 IOSTANDARD LVCMOS33} [get_ports GPIO10]
set_property -dict {PACKAGE_PIN A16 IOSTANDARD LVCMOS33} [get_ports GPIO11]
set_property -dict {PACKAGE_PIN A13 IOSTANDARD LVCMOS33} [get_ports GPIO12]
set_property -dict {PACKAGE_PIN A14 IOSTANDARD LVCMOS33} [get_ports GPIO13]
set_property -dict {PACKAGE_PIN B17 IOSTANDARD LVCMOS33} [get_ports GPIO14]
set_property -dict {PACKAGE_PIN B18 IOSTANDARD LVCMOS33} [get_ports GPIO15]
set_property -dict {PACKAGE_PIN C18 IOSTANDARD LVCMOS33} [get_ports GPIO20]
set_property -dict {PACKAGE_PIN C19 IOSTANDARD LVCMOS33} [get_ports GPIO21]
set_property -dict {PACKAGE_PIN B20 IOSTANDARD LVCMOS33} [get_ports GPIO22]
set_property -dict {PACKAGE_PIN A20 IOSTANDARD LVCMOS33} [get_ports GPIO23]
set_property -dict {PACKAGE_PIN A18 IOSTANDARD LVCMOS33} [get_ports GPIO24]
set_property -dict {PACKAGE_PIN A19 IOSTANDARD LVCMOS33} [get_ports GPIO25]
set_property -dict {PACKAGE_PIN D20 IOSTANDARD LVCMOS33} [get_ports GPIO26]
set_property -dict {PACKAGE_PIN C20 IOSTANDARD LVCMOS33} [get_ports GPIO27]
set_property -dict {PACKAGE_PIN C22 IOSTANDARD LVCMOS33} [get_ports GPIO30]
set_property -dict {PACKAGE_PIN B22 IOSTANDARD LVCMOS33} [get_ports GPIO31]
set_property -dict {PACKAGE_PIN B21 IOSTANDARD LVCMOS33} [get_ports GPIO32]
set_property -dict {PACKAGE_PIN A21 IOSTANDARD LVCMOS33} [get_ports GPIO33]
set_property -dict {PACKAGE_PIN E22 IOSTANDARD LVCMOS33} [get_ports GPIO34]
set_property -dict {PACKAGE_PIN D22 IOSTANDARD LVCMOS33} [get_ports GPIO35]

set_property -dict {PACKAGE_PIN G17 IOSTANDARD LVCMOS33} [get_ports GPIO40]
set_property -dict {PACKAGE_PIN G18 IOSTANDARD LVCMOS33} [get_ports GPIO41]
set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVCMOS33} [get_ports GPIO42]
set_property -dict {PACKAGE_PIN H18 IOSTANDARD LVCMOS33} [get_ports GPIO43]
set_property -dict {PACKAGE_PIN J22 IOSTANDARD LVCMOS33} [get_ports GPIO44]
set_property -dict {PACKAGE_PIN H22 IOSTANDARD LVCMOS33} [get_ports GPIO45]
set_property -dict {PACKAGE_PIN H20 IOSTANDARD LVCMOS33} [get_ports GPIO46]
set_property -dict {PACKAGE_PIN G20 IOSTANDARD LVCMOS33} [get_ports GPIO47]
set_property -dict {PACKAGE_PIN K21 IOSTANDARD LVCMOS33} [get_ports GPIO50]
set_property -dict {PACKAGE_PIN K22 IOSTANDARD LVCMOS33} [get_ports GPIO51]
set_property -dict {PACKAGE_PIN M21 IOSTANDARD LVCMOS33} [get_ports GPIO52]
set_property -dict {PACKAGE_PIN L21 IOSTANDARD LVCMOS33} [get_ports GPIO53]
set_property -dict {PACKAGE_PIN J20 IOSTANDARD LVCMOS33} [get_ports GPIO54]
set_property -dict {PACKAGE_PIN J21 IOSTANDARD LVCMOS33} [get_ports GPIO55]
set_property -dict {PACKAGE_PIN K18 IOSTANDARD LVCMOS33} [get_ports GPIO60]
set_property -dict {PACKAGE_PIN K19 IOSTANDARD LVCMOS33} [get_ports GPIO61]
set_property -dict {PACKAGE_PIN L19 IOSTANDARD LVCMOS33} [get_ports GPIO62]
set_property -dict {PACKAGE_PIN L20 IOSTANDARD LVCMOS33} [get_ports GPIO63]
set_property -dict {PACKAGE_PIN N22 IOSTANDARD LVCMOS33} [get_ports GPIO64]
set_property -dict {PACKAGE_PIN M22 IOSTANDARD LVCMOS33} [get_ports GPIO65]
set_property -dict {PACKAGE_PIN M18 IOSTANDARD LVCMOS33} [get_ports GPIO66]
set_property -dict {PACKAGE_PIN L18 IOSTANDARD LVCMOS33} [get_ports GPIO67]
set_property -dict {PACKAGE_PIN N18 IOSTANDARD LVCMOS33} [get_ports GPIO70]
set_property -dict {PACKAGE_PIN N19 IOSTANDARD LVCMOS33} [get_ports GPIO71]
set_property -dict {PACKAGE_PIN N20 IOSTANDARD LVCMOS33} [get_ports GPIO72]
set_property -dict {PACKAGE_PIN M20 IOSTANDARD LVCMOS33} [get_ports GPIO73]
set_property -dict {PACKAGE_PIN K17 IOSTANDARD LVCMOS33} [get_ports GPIO74]
set_property -dict {PACKAGE_PIN J17 IOSTANDARD LVCMOS33} [get_ports GPIO75]

set_property -dict {PACKAGE_PIN U22 IOSTANDARD TMDS_33} [get_ports HDMI0_D0_P]
set_property -dict {PACKAGE_PIN V22 IOSTANDARD TMDS_33} [get_ports HDMI0_D0_N]
set_property -dict {PACKAGE_PIN T21 IOSTANDARD TMDS_33} [get_ports HDMI0_D1_P]
set_property -dict {PACKAGE_PIN U21 IOSTANDARD TMDS_33} [get_ports HDMI0_D1_N]
set_property -dict {PACKAGE_PIN P19 IOSTANDARD TMDS_33} [get_ports HDMI0_D2_P]
set_property -dict {PACKAGE_PIN R19 IOSTANDARD TMDS_33} [get_ports HDMI0_D2_N]
set_property -dict {PACKAGE_PIN W21 IOSTANDARD LVCMOS33} [get_ports HDMI0_SCL]
set_property -dict {PACKAGE_PIN W22 IOSTANDARD LVCMOS33} [get_ports HDMI0_SDA]
set_property -dict {PACKAGE_PIN U20 IOSTANDARD TMDS_33} [get_ports HDMI0_CLK_P]
set_property -dict {PACKAGE_PIN V20 IOSTANDARD TMDS_33} [get_ports HDMI0_CLK_N]

set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVCMOS33} [get_ports HDMI1_D0_P]
set_property -dict {PACKAGE_PIN Y19 IOSTANDARD LVCMOS33} [get_ports HDMI1_D0_N]
set_property -dict {PACKAGE_PIN V18 IOSTANDARD LVCMOS33} [get_ports HDMI1_D1_P]
set_property -dict {PACKAGE_PIN V19 IOSTANDARD LVCMOS33} [get_ports HDMI1_D1_N]
set_property -dict {PACKAGE_PIN AA19 IOSTANDARD LVCMOS33} [get_ports HDMI1_D2_P]
set_property -dict {PACKAGE_PIN AB20 IOSTANDARD LVCMOS33} [get_ports HDMI1_D2_N]
set_property -dict {PACKAGE_PIN AA20 IOSTANDARD LVCMOS33} [get_ports HDMI1_SCL]
set_property -dict {PACKAGE_PIN AA21 IOSTANDARD LVCMOS33} [get_ports HDMI1_SDA]
set_property -dict {PACKAGE_PIN W19 IOSTANDARD LVCMOS33} [get_ports HDMI1_CLK_P]
set_property -dict {PACKAGE_PIN W20 IOSTANDARD LVCMOS33} [get_ports HDMI1_CLK_N]

set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVCMOS33} [get_ports {PMOD[0]}]
set_property -dict {PACKAGE_PIN T18 IOSTANDARD LVCMOS33} [get_ports {PMOD[1]}]
set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVCMOS33} [get_ports {PMOD[2]}]
set_property -dict {PACKAGE_PIN P17 IOSTANDARD LVCMOS33} [get_ports {PMOD[3]}]

set_property -dict {PACKAGE_PIN AA11 IOSTANDARD LVCMOS33} [get_ports GEPHY_INT_N]
set_property -dict {PACKAGE_PIN AA10 IOSTANDARD LVCMOS33} [get_ports GEPHY_MDC]
set_property -dict {PACKAGE_PIN AB10 IOSTANDARD LVCMOS33} [get_ports GEPHY_MDIO]

create_clock -period 5.000 -name sysclk [get_ports sys_clk_p]
create_clock -period 8.000 -name macclk -waveform {0.000 4.000} [get_ports GEPHY_MAC_CLK]
create_clock -period 8.000 -name rgmii_rxclk -waveform {2.200 6.200} [get_ports GEPHY_RCK]

## 90-degree shift from RCK
set_input_delay -clock [get_clocks rgmii_rxclk] -clock_fall -min -add_delay 1.000 [get_ports {GEPHY_RD[*]}]
set_input_delay -clock [get_clocks rgmii_rxclk] -clock_fall -max -add_delay 3.000 [get_ports {GEPHY_RD[*]}]
set_input_delay -clock [get_clocks rgmii_rxclk] -min -add_delay 1.000 [get_ports {GEPHY_RD[*]}]
set_input_delay -clock [get_clocks rgmii_rxclk] -max -add_delay 3.000 [get_ports {GEPHY_RD[*]}]
set_input_delay -clock [get_clocks rgmii_rxclk] -clock_fall -min -add_delay 1.000 [get_ports GEPHY_RXDV_ER]
set_input_delay -clock [get_clocks rgmii_rxclk] -clock_fall -max -add_delay 3.000 [get_ports GEPHY_RXDV_ER]
set_input_delay -clock [get_clocks rgmii_rxclk] -min -add_delay 1.000 [get_ports GEPHY_RXDV_ER]
set_input_delay -clock [get_clocks rgmii_rxclk] -max -add_delay 3.000 [get_ports GEPHY_RXDV_ER]

## 90-degree shift from TCK
create_generated_clock -name GEPHY_TCK -source [get_pins u_e7udpip/u_e7udpip/u_ether/u_gmiitx/miitxregs_a7.txclk_ddr/C] -divide_by 1 [get_ports GEPHY_TCK]
set_output_delay -clock [get_clocks GEPHY_TCK] -clock_fall -min -add_delay 1.000 [get_ports {GEPHY_TD[*]}]
set_output_delay -clock [get_clocks GEPHY_TCK] -clock_fall -max -add_delay 3.000 [get_ports {GEPHY_TD[*]}]
set_output_delay -clock [get_clocks GEPHY_TCK] -max -add_delay 3.000 [get_ports {GEPHY_TD[*]}]
set_output_delay -clock [get_clocks GEPHY_TCK] -max -add_delay 3.000 [get_ports {GEPHY_TD[*]}]

set_output_delay -clock [get_clocks GEPHY_TCK] -clock_fall -min -add_delay 1.000 [get_ports GEPHY_TXEN_ER]
set_output_delay -clock [get_clocks GEPHY_TCK] -clock_fall -max -add_delay 3.000 [get_ports GEPHY_TXEN_ER]
set_output_delay -clock [get_clocks GEPHY_TCK] -min -add_delay 1.000 [get_ports GEPHY_TXEN_ER]
set_output_delay -clock [get_clocks GEPHY_TCK] -max -add_delay 3.000 [get_ports GEPHY_TXEN_ER]


create_pblock pblock_u_e7udpip
add_cells_to_pblock [get_pblocks pblock_u_e7udpip] [get_cells -quiet [list u_e7udpip]]
resize_pblock [get_pblocks pblock_u_e7udpip] -add {CLOCKREGION_X0Y1:CLOCKREGION_X0Y1}

set_false_path -from [get_clocks rgmii_rxclk] -to [get_clocks -of_objects [get_pins clk_wiz_1_i/inst/mmcm_adv_inst/CLKOUT1]]
set_false_path -from [get_clocks -of_objects [get_pins clk_wiz_1_i/inst/mmcm_adv_inst/CLKOUT1]] -to [get_clocks rgmii_rxclk]

set_false_path -from [get_clocks -of_objects [get_pins u_mig_7series_0/u_mig_7series_0_mig/u_ddr3_infrastructure/plle2_i/CLKOUT1]] -to [get_clocks -of_objects [get_pins u_mig_7series_0/u_mig_7series_0_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]]
set_false_path -from [get_clocks -of_objects [get_pins u_mig_7series_0/u_mig_7series_0_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]] -to [get_clocks -of_objects [get_pins u_mig_7series_0/u_mig_7series_0_mig/u_ddr3_infrastructure/plle2_i/CLKOUT1]]

set_false_path -from [get_clocks -of_objects [get_pins u_mig_7series_0/u_mig_7series_0_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]] -to [get_clocks -of_objects [get_pins clk_wiz_1_i/inst/mmcm_adv_inst/CLKOUT1]]
set_false_path -from [get_clocks -of_objects [get_pins clk_wiz_1_i/inst/mmcm_adv_inst/CLKOUT1]] -to [get_clocks -of_objects [get_pins u_mig_7series_0/u_mig_7series_0_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]]

set_false_path -from [get_clocks -of_objects [get_pins u_mig_7series_0/u_mig_7series_0_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]] -to [get_clocks -of_objects [get_pins clk_wiz_1_i/inst/mmcm_adv_inst/CLKOUT0]]
set_false_path -from [get_clocks -of_objects [get_pins clk_wiz_1_i/inst/mmcm_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins u_mig_7series_0/u_mig_7series_0_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]]

set_false_path -from [get_clocks rgmii_rxclk] -to [get_clocks -of_objects [get_pins u_mig_7series_0/u_mig_7series_0_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]]
set_false_path -from [get_clocks -of_objects [get_pins u_mig_7series_0/u_mig_7series_0_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]] -to [get_clocks rgmii_rxclk]

set_false_path -from [get_clocks -of_objects [get_pins clk_wiz_1_i/inst/mmcm_adv_inst/CLKOUT1]] -to [get_clocks -of_objects [get_pins clk_wiz_2_i/inst/mmcm_adv_inst/CLKOUT1]]
set_false_path -from [get_clocks -of_objects [get_pins clk_wiz_2_i/inst/mmcm_adv_inst/CLKOUT1]] -to [get_clocks -of_objects [get_pins clk_wiz_1_i/inst/mmcm_adv_inst/CLKOUT1]]
set_false_path -from [get_clocks -of_objects [get_pins clk_wiz_2_i/inst/mmcm_adv_inst/CLKOUT1]] -to [get_clocks -of_objects [get_pins u_mig_7series_0/u_mig_7series_0_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]]
set_false_path -from [get_clocks -of_objects [get_pins u_mig_7series_0/u_mig_7series_0_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]] -to [get_clocks -of_objects [get_pins clk_wiz_2_i/inst/mmcm_adv_inst/CLKOUT1]]



set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]




connect_debug_port u_ila_0/probe0 [get_nets [list {hdmi_gen/hdmi_axi_addr/y_cnt[0]} {hdmi_gen/hdmi_axi_addr/y_cnt[1]} {hdmi_gen/hdmi_axi_addr/y_cnt[2]} {hdmi_gen/hdmi_axi_addr/y_cnt[3]} {hdmi_gen/hdmi_axi_addr/y_cnt[4]} {hdmi_gen/hdmi_axi_addr/y_cnt[5]} {hdmi_gen/hdmi_axi_addr/y_cnt[6]} {hdmi_gen/hdmi_axi_addr/y_cnt[7]} {hdmi_gen/hdmi_axi_addr/y_cnt[8]} {hdmi_gen/hdmi_axi_addr/y_cnt[9]} {hdmi_gen/hdmi_axi_addr/y_cnt[10]} {hdmi_gen/hdmi_axi_addr/y_cnt[11]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {hdmi_gen/buf_dout[0]} {hdmi_gen/buf_dout[1]} {hdmi_gen/buf_dout[2]} {hdmi_gen/buf_dout[3]} {hdmi_gen/buf_dout[4]} {hdmi_gen/buf_dout[5]} {hdmi_gen/buf_dout[6]} {hdmi_gen/buf_dout[7]} {hdmi_gen/buf_dout[8]} {hdmi_gen/buf_dout[9]} {hdmi_gen/buf_dout[10]} {hdmi_gen/buf_dout[11]} {hdmi_gen/buf_dout[12]} {hdmi_gen/buf_dout[13]} {hdmi_gen/buf_dout[14]} {hdmi_gen/buf_dout[15]} {hdmi_gen/buf_dout[16]} {hdmi_gen/buf_dout[17]} {hdmi_gen/buf_dout[18]} {hdmi_gen/buf_dout[19]} {hdmi_gen/buf_dout[20]} {hdmi_gen/buf_dout[21]} {hdmi_gen/buf_dout[22]} {hdmi_gen/buf_dout[23]} {hdmi_gen/buf_dout[24]} {hdmi_gen/buf_dout[25]} {hdmi_gen/buf_dout[26]} {hdmi_gen/buf_dout[27]} {hdmi_gen/buf_dout[28]} {hdmi_gen/buf_dout[29]} {hdmi_gen/buf_dout[30]} {hdmi_gen/buf_dout[31]}]]
connect_debug_port u_ila_0/probe3 [get_nets [list {hdmi_gen/hdmi_axi_addr/state[0]} {hdmi_gen/hdmi_axi_addr/state[1]} {hdmi_gen/hdmi_axi_addr/state[2]}]]
connect_debug_port u_ila_0/probe4 [get_nets [list {hdmi_gen/read_addr[0]} {hdmi_gen/read_addr[1]} {hdmi_gen/read_addr[2]} {hdmi_gen/read_addr[3]} {hdmi_gen/read_addr[4]} {hdmi_gen/read_addr[5]} {hdmi_gen/read_addr[6]} {hdmi_gen/read_addr[7]} {hdmi_gen/read_addr[8]} {hdmi_gen/read_addr[9]} {hdmi_gen/read_addr[10]} {hdmi_gen/read_addr[11]} {hdmi_gen/read_addr[12]} {hdmi_gen/read_addr[13]} {hdmi_gen/read_addr[14]} {hdmi_gen/read_addr[15]} {hdmi_gen/read_addr[16]} {hdmi_gen/read_addr[17]} {hdmi_gen/read_addr[18]} {hdmi_gen/read_addr[19]} {hdmi_gen/read_addr[20]} {hdmi_gen/read_addr[21]} {hdmi_gen/read_addr[22]} {hdmi_gen/read_addr[23]} {hdmi_gen/read_addr[24]} {hdmi_gen/read_addr[25]} {hdmi_gen/read_addr[26]} {hdmi_gen/read_addr[27]} {hdmi_gen/read_addr[28]} {hdmi_gen/read_addr[29]} {hdmi_gen/read_addr[30]} {hdmi_gen/read_addr[31]}]]
connect_debug_port u_ila_0/probe5 [get_nets [list hdmi_gen/buf_we]]
connect_debug_port u_ila_1/probe1 [get_nets [list hdmi_gen/prefetch_line]]

connect_debug_port u_ila_0/probe0 [get_nets [list {hdmi_gen/udp_hdmi_recv/ctrl_in[0]} {hdmi_gen/udp_hdmi_recv/ctrl_in[1]} {hdmi_gen/udp_hdmi_recv/ctrl_in[2]} {hdmi_gen/udp_hdmi_recv/ctrl_in[3]} {hdmi_gen/udp_hdmi_recv/ctrl_in[4]} {hdmi_gen/udp_hdmi_recv/ctrl_in[5]} {hdmi_gen/udp_hdmi_recv/ctrl_in[6]} {hdmi_gen/udp_hdmi_recv/ctrl_in[7]} {hdmi_gen/udp_hdmi_recv/ctrl_in[8]} {hdmi_gen/udp_hdmi_recv/ctrl_in[9]} {hdmi_gen/udp_hdmi_recv/ctrl_in[10]} {hdmi_gen/udp_hdmi_recv/ctrl_in[11]} {hdmi_gen/udp_hdmi_recv/ctrl_in[12]} {hdmi_gen/udp_hdmi_recv/ctrl_in[13]} {hdmi_gen/udp_hdmi_recv/ctrl_in[14]} {hdmi_gen/udp_hdmi_recv/ctrl_in[15]} {hdmi_gen/udp_hdmi_recv/ctrl_in[16]} {hdmi_gen/udp_hdmi_recv/ctrl_in[17]} {hdmi_gen/udp_hdmi_recv/ctrl_in[18]} {hdmi_gen/udp_hdmi_recv/ctrl_in[19]} {hdmi_gen/udp_hdmi_recv/ctrl_in[20]} {hdmi_gen/udp_hdmi_recv/ctrl_in[21]} {hdmi_gen/udp_hdmi_recv/ctrl_in[22]} {hdmi_gen/udp_hdmi_recv/ctrl_in[23]} {hdmi_gen/udp_hdmi_recv/ctrl_in[24]} {hdmi_gen/udp_hdmi_recv/ctrl_in[25]} {hdmi_gen/udp_hdmi_recv/ctrl_in[26]} {hdmi_gen/udp_hdmi_recv/ctrl_in[27]} {hdmi_gen/udp_hdmi_recv/ctrl_in[28]} {hdmi_gen/udp_hdmi_recv/ctrl_in[29]} {hdmi_gen/udp_hdmi_recv/ctrl_in[30]} {hdmi_gen/udp_hdmi_recv/ctrl_in[31]} {hdmi_gen/udp_hdmi_recv/ctrl_in[32]} {hdmi_gen/udp_hdmi_recv/ctrl_in[33]} {hdmi_gen/udp_hdmi_recv/ctrl_in[34]} {hdmi_gen/udp_hdmi_recv/ctrl_in[35]} {hdmi_gen/udp_hdmi_recv/ctrl_in[36]} {hdmi_gen/udp_hdmi_recv/ctrl_in[37]} {hdmi_gen/udp_hdmi_recv/ctrl_in[38]} {hdmi_gen/udp_hdmi_recv/ctrl_in[39]}]]
connect_debug_port u_ila_0/probe1 [get_nets [list {hdmi_gen/udp_hdmi_recv/state[0]} {hdmi_gen/udp_hdmi_recv/state[1]} {hdmi_gen/udp_hdmi_recv/state[2]} {hdmi_gen/udp_hdmi_recv/state[3]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {hdmi_gen/udp_hdmi_recv/r_data[0]} {hdmi_gen/udp_hdmi_recv/r_data[1]} {hdmi_gen/udp_hdmi_recv/r_data[2]} {hdmi_gen/udp_hdmi_recv/r_data[3]} {hdmi_gen/udp_hdmi_recv/r_data[4]} {hdmi_gen/udp_hdmi_recv/r_data[5]} {hdmi_gen/udp_hdmi_recv/r_data[6]} {hdmi_gen/udp_hdmi_recv/r_data[7]} {hdmi_gen/udp_hdmi_recv/r_data[8]} {hdmi_gen/udp_hdmi_recv/r_data[9]} {hdmi_gen/udp_hdmi_recv/r_data[10]} {hdmi_gen/udp_hdmi_recv/r_data[11]} {hdmi_gen/udp_hdmi_recv/r_data[12]} {hdmi_gen/udp_hdmi_recv/r_data[13]} {hdmi_gen/udp_hdmi_recv/r_data[14]} {hdmi_gen/udp_hdmi_recv/r_data[15]} {hdmi_gen/udp_hdmi_recv/r_data[16]} {hdmi_gen/udp_hdmi_recv/r_data[17]} {hdmi_gen/udp_hdmi_recv/r_data[18]} {hdmi_gen/udp_hdmi_recv/r_data[19]} {hdmi_gen/udp_hdmi_recv/r_data[20]} {hdmi_gen/udp_hdmi_recv/r_data[21]} {hdmi_gen/udp_hdmi_recv/r_data[22]} {hdmi_gen/udp_hdmi_recv/r_data[23]} {hdmi_gen/udp_hdmi_recv/r_data[24]} {hdmi_gen/udp_hdmi_recv/r_data[25]} {hdmi_gen/udp_hdmi_recv/r_data[26]} {hdmi_gen/udp_hdmi_recv/r_data[27]} {hdmi_gen/udp_hdmi_recv/r_data[28]} {hdmi_gen/udp_hdmi_recv/r_data[29]} {hdmi_gen/udp_hdmi_recv/r_data[30]} {hdmi_gen/udp_hdmi_recv/r_data[31]}]]
connect_debug_port u_ila_0/probe3 [get_nets [list {hdmi_gen/udp_hdmi_recv/data_in[0]} {hdmi_gen/udp_hdmi_recv/data_in[1]} {hdmi_gen/udp_hdmi_recv/data_in[2]} {hdmi_gen/udp_hdmi_recv/data_in[3]} {hdmi_gen/udp_hdmi_recv/data_in[4]} {hdmi_gen/udp_hdmi_recv/data_in[5]} {hdmi_gen/udp_hdmi_recv/data_in[6]} {hdmi_gen/udp_hdmi_recv/data_in[7]} {hdmi_gen/udp_hdmi_recv/data_in[8]} {hdmi_gen/udp_hdmi_recv/data_in[9]} {hdmi_gen/udp_hdmi_recv/data_in[10]} {hdmi_gen/udp_hdmi_recv/data_in[11]} {hdmi_gen/udp_hdmi_recv/data_in[12]} {hdmi_gen/udp_hdmi_recv/data_in[13]} {hdmi_gen/udp_hdmi_recv/data_in[14]} {hdmi_gen/udp_hdmi_recv/data_in[15]} {hdmi_gen/udp_hdmi_recv/data_in[16]} {hdmi_gen/udp_hdmi_recv/data_in[17]} {hdmi_gen/udp_hdmi_recv/data_in[18]} {hdmi_gen/udp_hdmi_recv/data_in[19]} {hdmi_gen/udp_hdmi_recv/data_in[20]} {hdmi_gen/udp_hdmi_recv/data_in[21]} {hdmi_gen/udp_hdmi_recv/data_in[22]} {hdmi_gen/udp_hdmi_recv/data_in[23]} {hdmi_gen/udp_hdmi_recv/data_in[24]} {hdmi_gen/udp_hdmi_recv/data_in[25]} {hdmi_gen/udp_hdmi_recv/data_in[26]} {hdmi_gen/udp_hdmi_recv/data_in[27]} {hdmi_gen/udp_hdmi_recv/data_in[28]} {hdmi_gen/udp_hdmi_recv/data_in[29]} {hdmi_gen/udp_hdmi_recv/data_in[30]} {hdmi_gen/udp_hdmi_recv/data_in[31]} {hdmi_gen/udp_hdmi_recv/data_in[32]} {hdmi_gen/udp_hdmi_recv/data_in[33]} {hdmi_gen/udp_hdmi_recv/data_in[34]} {hdmi_gen/udp_hdmi_recv/data_in[35]}]]
connect_debug_port u_ila_0/probe4 [get_nets [list {hdmi_gen/udp_hdmi_recv/w_data[0]} {hdmi_gen/udp_hdmi_recv/w_data[1]} {hdmi_gen/udp_hdmi_recv/w_data[2]} {hdmi_gen/udp_hdmi_recv/w_data[3]} {hdmi_gen/udp_hdmi_recv/w_data[4]} {hdmi_gen/udp_hdmi_recv/w_data[5]} {hdmi_gen/udp_hdmi_recv/w_data[6]} {hdmi_gen/udp_hdmi_recv/w_data[7]} {hdmi_gen/udp_hdmi_recv/w_data[8]} {hdmi_gen/udp_hdmi_recv/w_data[9]} {hdmi_gen/udp_hdmi_recv/w_data[10]} {hdmi_gen/udp_hdmi_recv/w_data[11]} {hdmi_gen/udp_hdmi_recv/w_data[12]} {hdmi_gen/udp_hdmi_recv/w_data[13]} {hdmi_gen/udp_hdmi_recv/w_data[14]} {hdmi_gen/udp_hdmi_recv/w_data[15]} {hdmi_gen/udp_hdmi_recv/w_data[16]} {hdmi_gen/udp_hdmi_recv/w_data[17]} {hdmi_gen/udp_hdmi_recv/w_data[18]} {hdmi_gen/udp_hdmi_recv/w_data[19]} {hdmi_gen/udp_hdmi_recv/w_data[20]} {hdmi_gen/udp_hdmi_recv/w_data[21]} {hdmi_gen/udp_hdmi_recv/w_data[22]} {hdmi_gen/udp_hdmi_recv/w_data[23]} {hdmi_gen/udp_hdmi_recv/w_data[24]} {hdmi_gen/udp_hdmi_recv/w_data[25]} {hdmi_gen/udp_hdmi_recv/w_data[26]} {hdmi_gen/udp_hdmi_recv/w_data[27]} {hdmi_gen/udp_hdmi_recv/w_data[28]} {hdmi_gen/udp_hdmi_recv/w_data[29]} {hdmi_gen/udp_hdmi_recv/w_data[30]} {hdmi_gen/udp_hdmi_recv/w_data[31]}]]
connect_debug_port u_ila_0/probe6 [get_nets [list hdmi_gen/udp_hdmi_recv/data_we]]
connect_debug_port u_ila_0/probe7 [get_nets [list hdmi_gen/udp_hdmi_recv/r_ack]]
connect_debug_port u_ila_0/probe8 [get_nets [list hdmi_gen/udp_hdmi_recv/r_enable]]
connect_debug_port u_ila_0/probe9 [get_nets [list hdmi_gen/udp_hdmi_recv/r_req]]
connect_debug_port u_ila_0/probe10 [get_nets [list hdmi_gen/udp_hdmi_recv/w_ack]]
connect_debug_port u_ila_0/probe11 [get_nets [list hdmi_gen/udp_hdmi_recv/w_enable]]
connect_debug_port u_ila_0/probe12 [get_nets [list hdmi_gen/udp_hdmi_recv/w_req]]






set_property OFFCHIP_TERM NONE [get_ports GEPHY_RST_N]
set_property OFFCHIP_TERM NONE [get_ports GEPHY_TCK]
set_property OFFCHIP_TERM NONE [get_ports GEPHY_TXEN_ER]
set_property OFFCHIP_TERM NONE [get_ports LED0]
set_property OFFCHIP_TERM NONE [get_ports LED1]
set_property OFFCHIP_TERM NONE [get_ports LED2]
set_property OFFCHIP_TERM NONE [get_ports GEPHY_TD[3]]
set_property OFFCHIP_TERM NONE [get_ports GEPHY_TD[2]]
set_property OFFCHIP_TERM NONE [get_ports GEPHY_TD[1]]
set_property OFFCHIP_TERM NONE [get_ports GEPHY_TD[0]]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list u_mig_7series_0/u_mig_7series_0_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i_0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {hdmi_gen/udp_hdmi_recv/ctrl_len[0]} {hdmi_gen/udp_hdmi_recv/ctrl_len[1]} {hdmi_gen/udp_hdmi_recv/ctrl_len[2]} {hdmi_gen/udp_hdmi_recv/ctrl_len[3]} {hdmi_gen/udp_hdmi_recv/ctrl_len[4]} {hdmi_gen/udp_hdmi_recv/ctrl_len[5]} {hdmi_gen/udp_hdmi_recv/ctrl_len[6]} {hdmi_gen/udp_hdmi_recv/ctrl_len[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {hdmi_gen/udp_hdmi_recv/cnt[0]} {hdmi_gen/udp_hdmi_recv/cnt[1]} {hdmi_gen/udp_hdmi_recv/cnt[2]} {hdmi_gen/udp_hdmi_recv/cnt[3]} {hdmi_gen/udp_hdmi_recv/cnt[4]} {hdmi_gen/udp_hdmi_recv/cnt[5]} {hdmi_gen/udp_hdmi_recv/cnt[6]} {hdmi_gen/udp_hdmi_recv/cnt[7]} {hdmi_gen/udp_hdmi_recv/cnt[8]} {hdmi_gen/udp_hdmi_recv/cnt[9]} {hdmi_gen/udp_hdmi_recv/cnt[10]} {hdmi_gen/udp_hdmi_recv/cnt[11]} {hdmi_gen/udp_hdmi_recv/cnt[12]} {hdmi_gen/udp_hdmi_recv/cnt[13]} {hdmi_gen/udp_hdmi_recv/cnt[14]} {hdmi_gen/udp_hdmi_recv/cnt[15]} {hdmi_gen/udp_hdmi_recv/cnt[16]} {hdmi_gen/udp_hdmi_recv/cnt[17]} {hdmi_gen/udp_hdmi_recv/cnt[18]} {hdmi_gen/udp_hdmi_recv/cnt[19]} {hdmi_gen/udp_hdmi_recv/cnt[20]} {hdmi_gen/udp_hdmi_recv/cnt[21]} {hdmi_gen/udp_hdmi_recv/cnt[22]} {hdmi_gen/udp_hdmi_recv/cnt[23]} {hdmi_gen/udp_hdmi_recv/cnt[24]} {hdmi_gen/udp_hdmi_recv/cnt[25]} {hdmi_gen/udp_hdmi_recv/cnt[26]} {hdmi_gen/udp_hdmi_recv/cnt[27]} {hdmi_gen/udp_hdmi_recv/cnt[28]} {hdmi_gen/udp_hdmi_recv/cnt[29]} {hdmi_gen/udp_hdmi_recv/cnt[30]} {hdmi_gen/udp_hdmi_recv/cnt[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 40 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {hdmi_gen/udp_hdmi_recv/ctrl_in[0]} {hdmi_gen/udp_hdmi_recv/ctrl_in[1]} {hdmi_gen/udp_hdmi_recv/ctrl_in[2]} {hdmi_gen/udp_hdmi_recv/ctrl_in[3]} {hdmi_gen/udp_hdmi_recv/ctrl_in[4]} {hdmi_gen/udp_hdmi_recv/ctrl_in[5]} {hdmi_gen/udp_hdmi_recv/ctrl_in[6]} {hdmi_gen/udp_hdmi_recv/ctrl_in[7]} {hdmi_gen/udp_hdmi_recv/ctrl_in[8]} {hdmi_gen/udp_hdmi_recv/ctrl_in[9]} {hdmi_gen/udp_hdmi_recv/ctrl_in[10]} {hdmi_gen/udp_hdmi_recv/ctrl_in[11]} {hdmi_gen/udp_hdmi_recv/ctrl_in[12]} {hdmi_gen/udp_hdmi_recv/ctrl_in[13]} {hdmi_gen/udp_hdmi_recv/ctrl_in[14]} {hdmi_gen/udp_hdmi_recv/ctrl_in[15]} {hdmi_gen/udp_hdmi_recv/ctrl_in[16]} {hdmi_gen/udp_hdmi_recv/ctrl_in[17]} {hdmi_gen/udp_hdmi_recv/ctrl_in[18]} {hdmi_gen/udp_hdmi_recv/ctrl_in[19]} {hdmi_gen/udp_hdmi_recv/ctrl_in[20]} {hdmi_gen/udp_hdmi_recv/ctrl_in[21]} {hdmi_gen/udp_hdmi_recv/ctrl_in[22]} {hdmi_gen/udp_hdmi_recv/ctrl_in[23]} {hdmi_gen/udp_hdmi_recv/ctrl_in[24]} {hdmi_gen/udp_hdmi_recv/ctrl_in[25]} {hdmi_gen/udp_hdmi_recv/ctrl_in[26]} {hdmi_gen/udp_hdmi_recv/ctrl_in[27]} {hdmi_gen/udp_hdmi_recv/ctrl_in[28]} {hdmi_gen/udp_hdmi_recv/ctrl_in[29]} {hdmi_gen/udp_hdmi_recv/ctrl_in[30]} {hdmi_gen/udp_hdmi_recv/ctrl_in[31]} {hdmi_gen/udp_hdmi_recv/ctrl_in[32]} {hdmi_gen/udp_hdmi_recv/ctrl_in[33]} {hdmi_gen/udp_hdmi_recv/ctrl_in[34]} {hdmi_gen/udp_hdmi_recv/ctrl_in[35]} {hdmi_gen/udp_hdmi_recv/ctrl_in[36]} {hdmi_gen/udp_hdmi_recv/ctrl_in[37]} {hdmi_gen/udp_hdmi_recv/ctrl_in[38]} {hdmi_gen/udp_hdmi_recv/ctrl_in[39]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {hdmi_gen/udp_hdmi_recv/ctrl_len_buf[0]} {hdmi_gen/udp_hdmi_recv/ctrl_len_buf[1]} {hdmi_gen/udp_hdmi_recv/ctrl_len_buf[2]} {hdmi_gen/udp_hdmi_recv/ctrl_len_buf[3]} {hdmi_gen/udp_hdmi_recv/ctrl_len_buf[4]} {hdmi_gen/udp_hdmi_recv/ctrl_len_buf[5]} {hdmi_gen/udp_hdmi_recv/ctrl_len_buf[6]} {hdmi_gen/udp_hdmi_recv/ctrl_len_buf[7]} {hdmi_gen/udp_hdmi_recv/ctrl_len_buf[8]} {hdmi_gen/udp_hdmi_recv/ctrl_len_buf[9]} {hdmi_gen/udp_hdmi_recv/ctrl_len_buf[10]} {hdmi_gen/udp_hdmi_recv/ctrl_len_buf[11]} {hdmi_gen/udp_hdmi_recv/ctrl_len_buf[12]} {hdmi_gen/udp_hdmi_recv/ctrl_len_buf[13]} {hdmi_gen/udp_hdmi_recv/ctrl_len_buf[14]} {hdmi_gen/udp_hdmi_recv/ctrl_len_buf[15]} {hdmi_gen/udp_hdmi_recv/ctrl_len_buf[16]} {hdmi_gen/udp_hdmi_recv/ctrl_len_buf[17]} {hdmi_gen/udp_hdmi_recv/ctrl_len_buf[18]} {hdmi_gen/udp_hdmi_recv/ctrl_len_buf[19]} {hdmi_gen/udp_hdmi_recv/ctrl_len_buf[20]} {hdmi_gen/udp_hdmi_recv/ctrl_len_buf[21]} {hdmi_gen/udp_hdmi_recv/ctrl_len_buf[22]} {hdmi_gen/udp_hdmi_recv/ctrl_len_buf[23]} {hdmi_gen/udp_hdmi_recv/ctrl_len_buf[24]} {hdmi_gen/udp_hdmi_recv/ctrl_len_buf[25]} {hdmi_gen/udp_hdmi_recv/ctrl_len_buf[26]} {hdmi_gen/udp_hdmi_recv/ctrl_len_buf[27]} {hdmi_gen/udp_hdmi_recv/ctrl_len_buf[28]} {hdmi_gen/udp_hdmi_recv/ctrl_len_buf[29]} {hdmi_gen/udp_hdmi_recv/ctrl_len_buf[30]} {hdmi_gen/udp_hdmi_recv/ctrl_len_buf[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {hdmi_gen/udp_hdmi_recv/r_data[0]} {hdmi_gen/udp_hdmi_recv/r_data[1]} {hdmi_gen/udp_hdmi_recv/r_data[2]} {hdmi_gen/udp_hdmi_recv/r_data[3]} {hdmi_gen/udp_hdmi_recv/r_data[4]} {hdmi_gen/udp_hdmi_recv/r_data[5]} {hdmi_gen/udp_hdmi_recv/r_data[6]} {hdmi_gen/udp_hdmi_recv/r_data[7]} {hdmi_gen/udp_hdmi_recv/r_data[8]} {hdmi_gen/udp_hdmi_recv/r_data[9]} {hdmi_gen/udp_hdmi_recv/r_data[10]} {hdmi_gen/udp_hdmi_recv/r_data[11]} {hdmi_gen/udp_hdmi_recv/r_data[12]} {hdmi_gen/udp_hdmi_recv/r_data[13]} {hdmi_gen/udp_hdmi_recv/r_data[14]} {hdmi_gen/udp_hdmi_recv/r_data[15]} {hdmi_gen/udp_hdmi_recv/r_data[16]} {hdmi_gen/udp_hdmi_recv/r_data[17]} {hdmi_gen/udp_hdmi_recv/r_data[18]} {hdmi_gen/udp_hdmi_recv/r_data[19]} {hdmi_gen/udp_hdmi_recv/r_data[20]} {hdmi_gen/udp_hdmi_recv/r_data[21]} {hdmi_gen/udp_hdmi_recv/r_data[22]} {hdmi_gen/udp_hdmi_recv/r_data[23]} {hdmi_gen/udp_hdmi_recv/r_data[24]} {hdmi_gen/udp_hdmi_recv/r_data[25]} {hdmi_gen/udp_hdmi_recv/r_data[26]} {hdmi_gen/udp_hdmi_recv/r_data[27]} {hdmi_gen/udp_hdmi_recv/r_data[28]} {hdmi_gen/udp_hdmi_recv/r_data[29]} {hdmi_gen/udp_hdmi_recv/r_data[30]} {hdmi_gen/udp_hdmi_recv/r_data[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 4 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {hdmi_gen/udp_hdmi_recv/state[0]} {hdmi_gen/udp_hdmi_recv/state[1]} {hdmi_gen/udp_hdmi_recv/state[2]} {hdmi_gen/udp_hdmi_recv/state[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 3 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {hdmi_gen/udp_hdmi_recv/ctrl_state[0]} {hdmi_gen/udp_hdmi_recv/ctrl_state[1]} {hdmi_gen/udp_hdmi_recv/ctrl_state[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 32 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {hdmi_gen/udp_hdmi_recv/offset_buf[0]} {hdmi_gen/udp_hdmi_recv/offset_buf[1]} {hdmi_gen/udp_hdmi_recv/offset_buf[2]} {hdmi_gen/udp_hdmi_recv/offset_buf[3]} {hdmi_gen/udp_hdmi_recv/offset_buf[4]} {hdmi_gen/udp_hdmi_recv/offset_buf[5]} {hdmi_gen/udp_hdmi_recv/offset_buf[6]} {hdmi_gen/udp_hdmi_recv/offset_buf[7]} {hdmi_gen/udp_hdmi_recv/offset_buf[8]} {hdmi_gen/udp_hdmi_recv/offset_buf[9]} {hdmi_gen/udp_hdmi_recv/offset_buf[10]} {hdmi_gen/udp_hdmi_recv/offset_buf[11]} {hdmi_gen/udp_hdmi_recv/offset_buf[12]} {hdmi_gen/udp_hdmi_recv/offset_buf[13]} {hdmi_gen/udp_hdmi_recv/offset_buf[14]} {hdmi_gen/udp_hdmi_recv/offset_buf[15]} {hdmi_gen/udp_hdmi_recv/offset_buf[16]} {hdmi_gen/udp_hdmi_recv/offset_buf[17]} {hdmi_gen/udp_hdmi_recv/offset_buf[18]} {hdmi_gen/udp_hdmi_recv/offset_buf[19]} {hdmi_gen/udp_hdmi_recv/offset_buf[20]} {hdmi_gen/udp_hdmi_recv/offset_buf[21]} {hdmi_gen/udp_hdmi_recv/offset_buf[22]} {hdmi_gen/udp_hdmi_recv/offset_buf[23]} {hdmi_gen/udp_hdmi_recv/offset_buf[24]} {hdmi_gen/udp_hdmi_recv/offset_buf[25]} {hdmi_gen/udp_hdmi_recv/offset_buf[26]} {hdmi_gen/udp_hdmi_recv/offset_buf[27]} {hdmi_gen/udp_hdmi_recv/offset_buf[28]} {hdmi_gen/udp_hdmi_recv/offset_buf[29]} {hdmi_gen/udp_hdmi_recv/offset_buf[30]} {hdmi_gen/udp_hdmi_recv/offset_buf[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 32 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {hdmi_gen/udp_hdmi_recv/w_data[0]} {hdmi_gen/udp_hdmi_recv/w_data[1]} {hdmi_gen/udp_hdmi_recv/w_data[2]} {hdmi_gen/udp_hdmi_recv/w_data[3]} {hdmi_gen/udp_hdmi_recv/w_data[4]} {hdmi_gen/udp_hdmi_recv/w_data[5]} {hdmi_gen/udp_hdmi_recv/w_data[6]} {hdmi_gen/udp_hdmi_recv/w_data[7]} {hdmi_gen/udp_hdmi_recv/w_data[8]} {hdmi_gen/udp_hdmi_recv/w_data[9]} {hdmi_gen/udp_hdmi_recv/w_data[10]} {hdmi_gen/udp_hdmi_recv/w_data[11]} {hdmi_gen/udp_hdmi_recv/w_data[12]} {hdmi_gen/udp_hdmi_recv/w_data[13]} {hdmi_gen/udp_hdmi_recv/w_data[14]} {hdmi_gen/udp_hdmi_recv/w_data[15]} {hdmi_gen/udp_hdmi_recv/w_data[16]} {hdmi_gen/udp_hdmi_recv/w_data[17]} {hdmi_gen/udp_hdmi_recv/w_data[18]} {hdmi_gen/udp_hdmi_recv/w_data[19]} {hdmi_gen/udp_hdmi_recv/w_data[20]} {hdmi_gen/udp_hdmi_recv/w_data[21]} {hdmi_gen/udp_hdmi_recv/w_data[22]} {hdmi_gen/udp_hdmi_recv/w_data[23]} {hdmi_gen/udp_hdmi_recv/w_data[24]} {hdmi_gen/udp_hdmi_recv/w_data[25]} {hdmi_gen/udp_hdmi_recv/w_data[26]} {hdmi_gen/udp_hdmi_recv/w_data[27]} {hdmi_gen/udp_hdmi_recv/w_data[28]} {hdmi_gen/udp_hdmi_recv/w_data[29]} {hdmi_gen/udp_hdmi_recv/w_data[30]} {hdmi_gen/udp_hdmi_recv/w_data[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 32 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {hdmi_gen/fifo_in[0]} {hdmi_gen/fifo_in[1]} {hdmi_gen/fifo_in[2]} {hdmi_gen/fifo_in[3]} {hdmi_gen/fifo_in[4]} {hdmi_gen/fifo_in[5]} {hdmi_gen/fifo_in[6]} {hdmi_gen/fifo_in[7]} {hdmi_gen/fifo_in[8]} {hdmi_gen/fifo_in[9]} {hdmi_gen/fifo_in[10]} {hdmi_gen/fifo_in[11]} {hdmi_gen/fifo_in[12]} {hdmi_gen/fifo_in[13]} {hdmi_gen/fifo_in[14]} {hdmi_gen/fifo_in[15]} {hdmi_gen/fifo_in[16]} {hdmi_gen/fifo_in[17]} {hdmi_gen/fifo_in[18]} {hdmi_gen/fifo_in[19]} {hdmi_gen/fifo_in[20]} {hdmi_gen/fifo_in[21]} {hdmi_gen/fifo_in[22]} {hdmi_gen/fifo_in[23]} {hdmi_gen/fifo_in[24]} {hdmi_gen/fifo_in[25]} {hdmi_gen/fifo_in[26]} {hdmi_gen/fifo_in[27]} {hdmi_gen/fifo_in[28]} {hdmi_gen/fifo_in[29]} {hdmi_gen/fifo_in[30]} {hdmi_gen/fifo_in[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 32 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {hdmi_gen/fifo_available[0]} {hdmi_gen/fifo_available[1]} {hdmi_gen/fifo_available[2]} {hdmi_gen/fifo_available[3]} {hdmi_gen/fifo_available[4]} {hdmi_gen/fifo_available[5]} {hdmi_gen/fifo_available[6]} {hdmi_gen/fifo_available[7]} {hdmi_gen/fifo_available[8]} {hdmi_gen/fifo_available[9]} {hdmi_gen/fifo_available[10]} {hdmi_gen/fifo_available[11]} {hdmi_gen/fifo_available[12]} {hdmi_gen/fifo_available[13]} {hdmi_gen/fifo_available[14]} {hdmi_gen/fifo_available[15]} {hdmi_gen/fifo_available[16]} {hdmi_gen/fifo_available[17]} {hdmi_gen/fifo_available[18]} {hdmi_gen/fifo_available[19]} {hdmi_gen/fifo_available[20]} {hdmi_gen/fifo_available[21]} {hdmi_gen/fifo_available[22]} {hdmi_gen/fifo_available[23]} {hdmi_gen/fifo_available[24]} {hdmi_gen/fifo_available[25]} {hdmi_gen/fifo_available[26]} {hdmi_gen/fifo_available[27]} {hdmi_gen/fifo_available[28]} {hdmi_gen/fifo_available[29]} {hdmi_gen/fifo_available[30]} {hdmi_gen/fifo_available[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 32 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {hdmi_gen/fifo_out_clk[0]_0[0]} {hdmi_gen/fifo_out_clk[0]_0[1]} {hdmi_gen/fifo_out_clk[0]_0[2]} {hdmi_gen/fifo_out_clk[0]_0[3]} {hdmi_gen/fifo_out_clk[0]_0[4]} {hdmi_gen/fifo_out_clk[0]_0[5]} {hdmi_gen/fifo_out_clk[0]_0[6]} {hdmi_gen/fifo_out_clk[0]_0[7]} {hdmi_gen/fifo_out_clk[0]_0[8]} {hdmi_gen/fifo_out_clk[0]_0[9]} {hdmi_gen/fifo_out_clk[0]_0[10]} {hdmi_gen/fifo_out_clk[0]_0[11]} {hdmi_gen/fifo_out_clk[0]_0[12]} {hdmi_gen/fifo_out_clk[0]_0[13]} {hdmi_gen/fifo_out_clk[0]_0[14]} {hdmi_gen/fifo_out_clk[0]_0[15]} {hdmi_gen/fifo_out_clk[0]_0[16]} {hdmi_gen/fifo_out_clk[0]_0[17]} {hdmi_gen/fifo_out_clk[0]_0[18]} {hdmi_gen/fifo_out_clk[0]_0[19]} {hdmi_gen/fifo_out_clk[0]_0[20]} {hdmi_gen/fifo_out_clk[0]_0[21]} {hdmi_gen/fifo_out_clk[0]_0[22]} {hdmi_gen/fifo_out_clk[0]_0[23]} {hdmi_gen/fifo_out_clk[0]_0[24]} {hdmi_gen/fifo_out_clk[0]_0[25]} {hdmi_gen/fifo_out_clk[0]_0[26]} {hdmi_gen/fifo_out_clk[0]_0[27]} {hdmi_gen/fifo_out_clk[0]_0[28]} {hdmi_gen/fifo_out_clk[0]_0[29]} {hdmi_gen/fifo_out_clk[0]_0[30]} {hdmi_gen/fifo_out_clk[0]_0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 32 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {hdmi_gen/fifo_out_clk[1]_1[0]} {hdmi_gen/fifo_out_clk[1]_1[1]} {hdmi_gen/fifo_out_clk[1]_1[2]} {hdmi_gen/fifo_out_clk[1]_1[3]} {hdmi_gen/fifo_out_clk[1]_1[4]} {hdmi_gen/fifo_out_clk[1]_1[5]} {hdmi_gen/fifo_out_clk[1]_1[6]} {hdmi_gen/fifo_out_clk[1]_1[7]} {hdmi_gen/fifo_out_clk[1]_1[8]} {hdmi_gen/fifo_out_clk[1]_1[9]} {hdmi_gen/fifo_out_clk[1]_1[10]} {hdmi_gen/fifo_out_clk[1]_1[11]} {hdmi_gen/fifo_out_clk[1]_1[12]} {hdmi_gen/fifo_out_clk[1]_1[13]} {hdmi_gen/fifo_out_clk[1]_1[14]} {hdmi_gen/fifo_out_clk[1]_1[15]} {hdmi_gen/fifo_out_clk[1]_1[16]} {hdmi_gen/fifo_out_clk[1]_1[17]} {hdmi_gen/fifo_out_clk[1]_1[18]} {hdmi_gen/fifo_out_clk[1]_1[19]} {hdmi_gen/fifo_out_clk[1]_1[20]} {hdmi_gen/fifo_out_clk[1]_1[21]} {hdmi_gen/fifo_out_clk[1]_1[22]} {hdmi_gen/fifo_out_clk[1]_1[23]} {hdmi_gen/fifo_out_clk[1]_1[24]} {hdmi_gen/fifo_out_clk[1]_1[25]} {hdmi_gen/fifo_out_clk[1]_1[26]} {hdmi_gen/fifo_out_clk[1]_1[27]} {hdmi_gen/fifo_out_clk[1]_1[28]} {hdmi_gen/fifo_out_clk[1]_1[29]} {hdmi_gen/fifo_out_clk[1]_1[30]} {hdmi_gen/fifo_out_clk[1]_1[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 2 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {hdmi_gen/framestart_clk[0]} {hdmi_gen/framestart_clk[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list hdmi_gen/udp_hdmi_recv/ctrl_we]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list hdmi_gen/udp_hdmi_recv/r_ack]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list hdmi_gen/udp_hdmi_recv/r_enable]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list hdmi_gen/udp_hdmi_recv/r_req]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list hdmi_gen/udp_hdmi_recv/w_ack]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list hdmi_gen/udp_hdmi_recv/w_enable]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list hdmi_gen/udp_hdmi_recv/w_req]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list clk_wiz_2_i/inst/clk_out2]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 32 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {hdmi_gen/fifo_out[0]} {hdmi_gen/fifo_out[1]} {hdmi_gen/fifo_out[2]} {hdmi_gen/fifo_out[3]} {hdmi_gen/fifo_out[4]} {hdmi_gen/fifo_out[5]} {hdmi_gen/fifo_out[6]} {hdmi_gen/fifo_out[7]} {hdmi_gen/fifo_out[8]} {hdmi_gen/fifo_out[9]} {hdmi_gen/fifo_out[10]} {hdmi_gen/fifo_out[11]} {hdmi_gen/fifo_out[12]} {hdmi_gen/fifo_out[13]} {hdmi_gen/fifo_out[14]} {hdmi_gen/fifo_out[15]} {hdmi_gen/fifo_out[16]} {hdmi_gen/fifo_out[17]} {hdmi_gen/fifo_out[18]} {hdmi_gen/fifo_out[19]} {hdmi_gen/fifo_out[20]} {hdmi_gen/fifo_out[21]} {hdmi_gen/fifo_out[22]} {hdmi_gen/fifo_out[23]} {hdmi_gen/fifo_out[24]} {hdmi_gen/fifo_out[25]} {hdmi_gen/fifo_out[26]} {hdmi_gen/fifo_out[27]} {hdmi_gen/fifo_out[28]} {hdmi_gen/fifo_out[29]} {hdmi_gen/fifo_out[30]} {hdmi_gen/fifo_out[31]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_vga]
