set_property -dict {PACKAGE_PIN AA14 IOSTANDARD LVCMOS33} [get_ports {GEPHY_RD[3]}]
set_property -dict {PACKAGE_PIN Y13 IOSTANDARD LVCMOS33} [get_ports {GEPHY_RD[2]}]
set_property -dict {PACKAGE_PIN AB15 IOSTANDARD LVCMOS33} [get_ports {GEPHY_RD[1]}]
set_property -dict {PACKAGE_PIN AA15 IOSTANDARD LVCMOS33} [get_ports {GEPHY_RD[0]}]
set_property -dict {PACKAGE_PIN AB17 IOSTANDARD LVCMOS33} [get_ports {GEPHY_TD[3]}]
set_property -dict {PACKAGE_PIN AB16 IOSTANDARD LVCMOS33} [get_ports {GEPHY_TD[2]}]
set_property -dict {PACKAGE_PIN AA16 IOSTANDARD LVCMOS33} [get_ports {GEPHY_TD[1]}]
set_property -dict {PACKAGE_PIN Y16 IOSTANDARD LVCMOS33} [get_ports {GEPHY_TD[0]}]
set_property -dict {PACKAGE_PIN W11 IOSTANDARD LVCMOS33} [get_ports GEPHY_MAC_CLK]
set_property -dict {PACKAGE_PIN T16 IOSTANDARD LVCMOS33} [get_ports GEPHY_PMEB]
set_property -dict {PACKAGE_PIN Y11 IOSTANDARD LVCMOS33} [get_ports GEPHY_RCK]
set_property -dict {PACKAGE_PIN U16 IOSTANDARD LVCMOS33} [get_ports GEPHY_RST_N]
set_property -dict {PACKAGE_PIN AA9 IOSTANDARD LVCMOS33} [get_ports GEPHY_RXDV_ER]
set_property -dict {PACKAGE_PIN AB13 IOSTANDARD LVCMOS33} [get_ports GEPHY_TCK]
set_property -dict {PACKAGE_PIN AA13 IOSTANDARD LVCMOS33} [get_ports GEPHY_TXEN_ER]
set_property -dict {PACKAGE_PIN E21 IOSTANDARD LVCMOS33} [get_ports LED0]
set_property -dict {PACKAGE_PIN D21 IOSTANDARD LVCMOS33} [get_ports LED1]
set_property -dict {PACKAGE_PIN G22 IOSTANDARD LVCMOS33} [get_ports LED2]
set_property -dict {PACKAGE_PIN H4 IOSTANDARD LVDS_25} [get_ports sys_clk_p]
set_property -dict {PACKAGE_PIN G4 IOSTANDARD LVDS_25} [get_ports sys_clk_n]
set_property -dict {PACKAGE_PIN D19 IOSTANDARD LVCMOS33} [get_ports sys_rst_n]

set_property -dict {PACKAGE_PIN C14 IOSTANDARD LVCMOS33} [get_ports GPIO00]
set_property -dict {PACKAGE_PIN C15 IOSTANDARD LVCMOS33} [get_ports GPIO01]
set_property -dict {PACKAGE_PIN D14 IOSTANDARD LVCMOS33} [get_ports GPIO02]
set_property -dict {PACKAGE_PIN D15 IOSTANDARD LVCMOS33} [get_ports GPIO03]
set_property -dict {PACKAGE_PIN B15 IOSTANDARD LVCMOS33} [get_ports GPIO04]
set_property -dict {PACKAGE_PIN B16 IOSTANDARD LVCMOS33} [get_ports GPIO05]
set_property -dict {PACKAGE_PIN C13 IOSTANDARD LVCMOS33} [get_ports GPIO06]
set_property -dict {PACKAGE_PIN B13 IOSTANDARD LVCMOS33} [get_ports GPIO07]
set_property -dict {PACKAGE_PIN A15 IOSTANDARD LVCMOS33} [get_ports GPIO10]
set_property -dict {PACKAGE_PIN A16 IOSTANDARD LVCMOS33} [get_ports GPIO11]
set_property -dict {PACKAGE_PIN A13 IOSTANDARD LVCMOS33} [get_ports GPIO12]
set_property -dict {PACKAGE_PIN A14 IOSTANDARD LVCMOS33} [get_ports GPIO13]
set_property -dict {PACKAGE_PIN B17 IOSTANDARD LVCMOS33} [get_ports GPIO14]
set_property -dict {PACKAGE_PIN B18 IOSTANDARD LVCMOS33} [get_ports GPIO15]
set_property -dict {PACKAGE_PIN C18 IOSTANDARD LVCMOS33} [get_ports GPIO20]
set_property -dict {PACKAGE_PIN C19 IOSTANDARD LVCMOS33} [get_ports GPIO21]
set_property -dict {PACKAGE_PIN B20 IOSTANDARD LVCMOS33} [get_ports GPIO22]
set_property -dict {PACKAGE_PIN A20 IOSTANDARD LVCMOS33} [get_ports GPIO23]
set_property -dict {PACKAGE_PIN A18 IOSTANDARD LVCMOS33} [get_ports GPIO24]
set_property -dict {PACKAGE_PIN A19 IOSTANDARD LVCMOS33} [get_ports GPIO25]
set_property -dict {PACKAGE_PIN D20 IOSTANDARD LVCMOS33} [get_ports GPIO26]
set_property -dict {PACKAGE_PIN C20 IOSTANDARD LVCMOS33} [get_ports GPIO27]
set_property -dict {PACKAGE_PIN C22 IOSTANDARD LVCMOS33} [get_ports GPIO30]
set_property -dict {PACKAGE_PIN B22 IOSTANDARD LVCMOS33} [get_ports GPIO31]
set_property -dict {PACKAGE_PIN B21 IOSTANDARD LVCMOS33} [get_ports GPIO32]
set_property -dict {PACKAGE_PIN A21 IOSTANDARD LVCMOS33} [get_ports GPIO33]
set_property -dict {PACKAGE_PIN E22 IOSTANDARD LVCMOS33} [get_ports GPIO34]
set_property -dict {PACKAGE_PIN D22 IOSTANDARD LVCMOS33} [get_ports GPIO35]

set_property -dict {PACKAGE_PIN G17 IOSTANDARD LVCMOS33} [get_ports GPIO40]
set_property -dict {PACKAGE_PIN G18 IOSTANDARD LVCMOS33} [get_ports GPIO41]
set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVCMOS33} [get_ports GPIO42]
set_property -dict {PACKAGE_PIN H18 IOSTANDARD LVCMOS33} [get_ports GPIO43]
set_property -dict {PACKAGE_PIN J22 IOSTANDARD LVCMOS33} [get_ports GPIO44]
set_property -dict {PACKAGE_PIN H22 IOSTANDARD LVCMOS33} [get_ports GPIO45]
set_property -dict {PACKAGE_PIN H20 IOSTANDARD LVCMOS33} [get_ports GPIO46]
set_property -dict {PACKAGE_PIN G20 IOSTANDARD LVCMOS33} [get_ports GPIO47]
set_property -dict {PACKAGE_PIN K21 IOSTANDARD LVCMOS33} [get_ports GPIO50]
set_property -dict {PACKAGE_PIN K22 IOSTANDARD LVCMOS33} [get_ports GPIO51]
set_property -dict {PACKAGE_PIN M21 IOSTANDARD LVCMOS33} [get_ports GPIO52]
set_property -dict {PACKAGE_PIN L21 IOSTANDARD LVCMOS33} [get_ports GPIO53]
set_property -dict {PACKAGE_PIN J20 IOSTANDARD LVCMOS33} [get_ports GPIO54]
set_property -dict {PACKAGE_PIN J21 IOSTANDARD LVCMOS33} [get_ports GPIO55]
set_property -dict {PACKAGE_PIN K18 IOSTANDARD LVCMOS33} [get_ports GPIO60]
set_property -dict {PACKAGE_PIN K19 IOSTANDARD LVCMOS33} [get_ports GPIO61]
set_property -dict {PACKAGE_PIN L19 IOSTANDARD LVCMOS33} [get_ports GPIO62]
set_property -dict {PACKAGE_PIN L20 IOSTANDARD LVCMOS33} [get_ports GPIO63]
set_property -dict {PACKAGE_PIN N22 IOSTANDARD LVCMOS33} [get_ports GPIO64]
set_property -dict {PACKAGE_PIN M22 IOSTANDARD LVCMOS33} [get_ports GPIO65]
set_property -dict {PACKAGE_PIN M18 IOSTANDARD LVCMOS33} [get_ports GPIO66]
set_property -dict {PACKAGE_PIN L18 IOSTANDARD LVCMOS33} [get_ports GPIO67]
set_property -dict {PACKAGE_PIN N18 IOSTANDARD LVCMOS33} [get_ports GPIO70]
set_property -dict {PACKAGE_PIN N19 IOSTANDARD LVCMOS33} [get_ports GPIO71]
set_property -dict {PACKAGE_PIN N20 IOSTANDARD LVCMOS33} [get_ports GPIO72]
set_property -dict {PACKAGE_PIN M20 IOSTANDARD LVCMOS33} [get_ports GPIO73]
set_property -dict {PACKAGE_PIN K17 IOSTANDARD LVCMOS33} [get_ports GPIO74]
set_property -dict {PACKAGE_PIN J17 IOSTANDARD LVCMOS33} [get_ports GPIO75]

set_property -dict {PACKAGE_PIN U22 IOSTANDARD LVCMOS33} [get_ports HDMI0_D0_P]
set_property -dict {PACKAGE_PIN V22 IOSTANDARD LVCMOS33} [get_ports HDMI0_D0_N]
set_property -dict {PACKAGE_PIN T21 IOSTANDARD LVCMOS33} [get_ports HDMI0_D1_P]
set_property -dict {PACKAGE_PIN U21 IOSTANDARD LVCMOS33} [get_ports HDMI0_D1_N]
set_property -dict {PACKAGE_PIN P19 IOSTANDARD LVCMOS33} [get_ports HDMI0_D2_P]
set_property -dict {PACKAGE_PIN R19 IOSTANDARD LVCMOS33} [get_ports HDMI0_D2_N]
set_property -dict {PACKAGE_PIN W21 IOSTANDARD LVCMOS33} [get_ports HDMI0_SCL]
set_property -dict {PACKAGE_PIN W22 IOSTANDARD LVCMOS33} [get_ports HDMI0_SDA]
set_property -dict {PACKAGE_PIN U20 IOSTANDARD LVCMOS33} [get_ports HDMI0_CLK_P]
set_property -dict {PACKAGE_PIN V20 IOSTANDARD LVCMOS33} [get_ports HDMI0_CLK_N]

set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVCMOS33} [get_ports HDMI1_D0_P]
set_property -dict {PACKAGE_PIN Y19 IOSTANDARD LVCMOS33} [get_ports HDMI1_D0_N]
set_property -dict {PACKAGE_PIN V18 IOSTANDARD LVCMOS33} [get_ports HDMI1_D1_P]
set_property -dict {PACKAGE_PIN V19 IOSTANDARD LVCMOS33} [get_ports HDMI1_D1_N]
set_property -dict {PACKAGE_PIN AA19 IOSTANDARD LVCMOS33} [get_ports HDMI1_D2_P]
set_property -dict {PACKAGE_PIN AB20 IOSTANDARD LVCMOS33} [get_ports HDMI1_D2_N]
set_property -dict {PACKAGE_PIN AA20 IOSTANDARD LVCMOS33} [get_ports HDMI1_SCL]
set_property -dict {PACKAGE_PIN AA21 IOSTANDARD LVCMOS33} [get_ports HDMI1_SDA]
set_property -dict {PACKAGE_PIN W19 IOSTANDARD LVCMOS33} [get_ports HDMI1_CLK_P]
set_property -dict {PACKAGE_PIN W20 IOSTANDARD LVCMOS33} [get_ports HDMI1_CLK_N]

set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVCMOS33} [get_ports {PMOD[0]}]
set_property -dict {PACKAGE_PIN T18 IOSTANDARD LVCMOS33} [get_ports {PMOD[1]}]
set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVCMOS33} [get_ports {PMOD[2]}]
set_property -dict {PACKAGE_PIN P17 IOSTANDARD LVCMOS33} [get_ports {PMOD[3]}]

set_property -dict {PACKAGE_PIN AA11 IOSTANDARD LVCMOS33} [get_ports GEPHY_INT_N]
set_property -dict {PACKAGE_PIN AA10 IOSTANDARD LVCMOS33} [get_ports GEPHY_MDC]
set_property -dict {PACKAGE_PIN AB10 IOSTANDARD LVCMOS33} [get_ports GEPHY_MDIO]

create_clock -period 5.000 -name sysclk [get_ports sys_clk_p]
create_clock -period 8.000 -name macclk -waveform {0.000 4.000} [get_ports GEPHY_MAC_CLK]
create_clock -period 8.000 -name rgmii_rxclk -waveform {2.200 6.200} [get_ports GEPHY_RCK]

## 90-degree shift from RCK
set_input_delay -clock [get_clocks rgmii_rxclk] -clock_fall -min -add_delay 1.000 [get_ports {GEPHY_RD[*]}]
set_input_delay -clock [get_clocks rgmii_rxclk] -clock_fall -max -add_delay 3.000 [get_ports {GEPHY_RD[*]}]
set_input_delay -clock [get_clocks rgmii_rxclk] -min -add_delay 1.000 [get_ports {GEPHY_RD[*]}]
set_input_delay -clock [get_clocks rgmii_rxclk] -max -add_delay 3.000 [get_ports {GEPHY_RD[*]}]
set_input_delay -clock [get_clocks rgmii_rxclk] -clock_fall -min -add_delay 1.000 [get_ports GEPHY_RXDV_ER]
set_input_delay -clock [get_clocks rgmii_rxclk] -clock_fall -max -add_delay 3.000 [get_ports GEPHY_RXDV_ER]
set_input_delay -clock [get_clocks rgmii_rxclk] -min -add_delay 1.000 [get_ports GEPHY_RXDV_ER]
set_input_delay -clock [get_clocks rgmii_rxclk] -max -add_delay 3.000 [get_ports GEPHY_RXDV_ER]

create_pblock pblock_u_e7udpip
add_cells_to_pblock [get_pblocks pblock_u_e7udpip] [get_cells -quiet [list u_e7udpip]]
resize_pblock [get_pblocks pblock_u_e7udpip] -add {CLOCKREGION_X0Y1:CLOCKREGION_X0Y1}

set_false_path -from [get_clocks rgmii_rxclk] -to [get_clocks -of_objects [get_pins clk_wiz_1_i/inst/mmcm_adv_inst/CLKOUT1]]
set_false_path -from [get_clocks -of_objects [get_pins clk_wiz_1_i/inst/mmcm_adv_inst/CLKOUT1]] -to [get_clocks rgmii_rxclk]

set_false_path -from [get_clocks -of_objects [get_pins u_mig_7series_0/u_mig_7series_0_mig/u_ddr3_infrastructure/plle2_i/CLKOUT1]] -to [get_clocks -of_objects [get_pins u_mig_7series_0/u_mig_7series_0_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]]
set_false_path -from [get_clocks -of_objects [get_pins u_mig_7series_0/u_mig_7series_0_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]] -to [get_clocks -of_objects [get_pins u_mig_7series_0/u_mig_7series_0_mig/u_ddr3_infrastructure/plle2_i/CLKOUT1]]

set_false_path -from [get_clocks -of_objects [get_pins u_mig_7series_0/u_mig_7series_0_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]] -to [get_clocks -of_objects [get_pins clk_wiz_1_i/inst/mmcm_adv_inst/CLKOUT1]]
set_false_path -from [get_clocks -of_objects [get_pins clk_wiz_1_i/inst/mmcm_adv_inst/CLKOUT1]] -to [get_clocks -of_objects [get_pins u_mig_7series_0/u_mig_7series_0_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]]

set_false_path -from [get_clocks -of_objects [get_pins u_mig_7series_0/u_mig_7series_0_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]] -to [get_clocks -of_objects [get_pins clk_wiz_1_i/inst/mmcm_adv_inst/CLKOUT0]]
set_false_path -from [get_clocks -of_objects [get_pins clk_wiz_1_i/inst/mmcm_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins u_mig_7series_0/u_mig_7series_0_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]]

set_false_path -from [get_clocks rgmii_rxclk] -to [get_clocks -of_objects [get_pins u_mig_7series_0/u_mig_7series_0_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]]
set_false_path -from [get_clocks -of_objects [get_pins u_mig_7series_0/u_mig_7series_0_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]] -to [get_clocks rgmii_rxclk]


set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]



connect_debug_port u_ila_0/probe0 [get_nets [list {udp_axi/buf_dout[0]} {udp_axi/buf_dout[1]} {udp_axi/buf_dout[2]} {udp_axi/buf_dout[3]} {udp_axi/buf_dout[4]} {udp_axi/buf_dout[5]} {udp_axi/buf_dout[6]} {udp_axi/buf_dout[7]} {udp_axi/buf_dout[8]} {udp_axi/buf_dout[9]} {udp_axi/buf_dout[10]} {udp_axi/buf_dout[11]} {udp_axi/buf_dout[12]} {udp_axi/buf_dout[13]} {udp_axi/buf_dout[14]} {udp_axi/buf_dout[15]} {udp_axi/buf_dout[16]} {udp_axi/buf_dout[17]} {udp_axi/buf_dout[18]} {udp_axi/buf_dout[19]} {udp_axi/buf_dout[20]} {udp_axi/buf_dout[21]} {udp_axi/buf_dout[22]} {udp_axi/buf_dout[23]} {udp_axi/buf_dout[24]} {udp_axi/buf_dout[25]} {udp_axi/buf_dout[26]} {udp_axi/buf_dout[27]} {udp_axi/buf_dout[28]} {udp_axi/buf_dout[29]} {udp_axi/buf_dout[30]} {udp_axi/buf_dout[31]}]]
connect_debug_port u_ila_0/probe1 [get_nets [list {udp_axi/r_data[0]} {udp_axi/r_data[1]} {udp_axi/r_data[2]} {udp_axi/r_data[3]} {udp_axi/r_data[4]} {udp_axi/r_data[5]} {udp_axi/r_data[6]} {udp_axi/r_data[7]} {udp_axi/r_data[8]} {udp_axi/r_data[9]} {udp_axi/r_data[10]} {udp_axi/r_data[11]} {udp_axi/r_data[12]} {udp_axi/r_data[13]} {udp_axi/r_data[14]} {udp_axi/r_data[15]} {udp_axi/r_data[16]} {udp_axi/r_data[17]} {udp_axi/r_data[18]} {udp_axi/r_data[19]} {udp_axi/r_data[20]} {udp_axi/r_data[21]} {udp_axi/r_data[22]} {udp_axi/r_data[23]} {udp_axi/r_data[24]} {udp_axi/r_data[25]} {udp_axi/r_data[26]} {udp_axi/r_data[27]} {udp_axi/r_data[28]} {udp_axi/r_data[29]} {udp_axi/r_data[30]} {udp_axi/r_data[31]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list udp_axi/buf_we]]
connect_debug_port u_ila_0/probe4 [get_nets [list udp_axi/r_ack]]
connect_debug_port u_ila_0/probe5 [get_nets [list udp_axi/r_req]]
connect_debug_port u_ila_0/probe6 [get_nets [list udp_axi/w_ack]]
connect_debug_port u_ila_1/probe0 [get_nets [list {udp_axi/data_in[0]} {udp_axi/data_in[1]} {udp_axi/data_in[2]} {udp_axi/data_in[3]} {udp_axi/data_in[4]} {udp_axi/data_in[5]} {udp_axi/data_in[6]} {udp_axi/data_in[7]} {udp_axi/data_in[8]} {udp_axi/data_in[9]} {udp_axi/data_in[10]} {udp_axi/data_in[11]} {udp_axi/data_in[12]} {udp_axi/data_in[13]} {udp_axi/data_in[14]} {udp_axi/data_in[15]} {udp_axi/data_in[16]} {udp_axi/data_in[17]} {udp_axi/data_in[18]} {udp_axi/data_in[19]} {udp_axi/data_in[20]} {udp_axi/data_in[21]} {udp_axi/data_in[22]} {udp_axi/data_in[23]} {udp_axi/data_in[24]} {udp_axi/data_in[25]} {udp_axi/data_in[26]} {udp_axi/data_in[27]} {udp_axi/data_in[28]} {udp_axi/data_in[29]} {udp_axi/data_in[30]} {udp_axi/data_in[31]} {udp_axi/data_in[32]} {udp_axi/data_in[33]} {udp_axi/data_in[34]} {udp_axi/data_in[35]}]]
connect_debug_port u_ila_1/probe1 [get_nets [list {udp_axi/ctrl_in[0]} {udp_axi/ctrl_in[1]} {udp_axi/ctrl_in[2]} {udp_axi/ctrl_in[3]} {udp_axi/ctrl_in[4]} {udp_axi/ctrl_in[5]} {udp_axi/ctrl_in[6]} {udp_axi/ctrl_in[7]} {udp_axi/ctrl_in[8]} {udp_axi/ctrl_in[9]} {udp_axi/ctrl_in[10]} {udp_axi/ctrl_in[11]} {udp_axi/ctrl_in[12]} {udp_axi/ctrl_in[13]} {udp_axi/ctrl_in[14]} {udp_axi/ctrl_in[15]} {udp_axi/ctrl_in[16]} {udp_axi/ctrl_in[17]} {udp_axi/ctrl_in[18]} {udp_axi/ctrl_in[19]} {udp_axi/ctrl_in[20]} {udp_axi/ctrl_in[21]} {udp_axi/ctrl_in[22]} {udp_axi/ctrl_in[23]} {udp_axi/ctrl_in[24]} {udp_axi/ctrl_in[25]} {udp_axi/ctrl_in[26]} {udp_axi/ctrl_in[27]} {udp_axi/ctrl_in[28]} {udp_axi/ctrl_in[29]} {udp_axi/ctrl_in[30]} {udp_axi/ctrl_in[31]} {udp_axi/ctrl_in[32]} {udp_axi/ctrl_in[33]} {udp_axi/ctrl_in[34]} {udp_axi/ctrl_in[35]} {udp_axi/ctrl_in[36]} {udp_axi/ctrl_in[37]} {udp_axi/ctrl_in[38]} {udp_axi/ctrl_in[39]}]]
connect_debug_port u_ila_1/probe2 [get_nets [list {udp_axi/read_num[0]} {udp_axi/read_num[1]} {udp_axi/read_num[2]} {udp_axi/read_num[3]} {udp_axi/read_num[4]} {udp_axi/read_num[5]} {udp_axi/read_num[6]} {udp_axi/read_num[7]} {udp_axi/read_num[8]} {udp_axi/read_num[9]} {udp_axi/read_num[10]} {udp_axi/read_num[11]} {udp_axi/read_num[12]} {udp_axi/read_num[13]} {udp_axi/read_num[14]} {udp_axi/read_num[15]} {udp_axi/read_num[16]} {udp_axi/read_num[17]} {udp_axi/read_num[18]} {udp_axi/read_num[19]} {udp_axi/read_num[20]} {udp_axi/read_num[21]} {udp_axi/read_num[22]} {udp_axi/read_num[23]} {udp_axi/read_num[24]} {udp_axi/read_num[25]} {udp_axi/read_num[26]} {udp_axi/read_num[27]} {udp_axi/read_num[28]} {udp_axi/read_num[29]} {udp_axi/read_num[30]} {udp_axi/read_num[31]}]]
connect_debug_port u_ila_1/probe3 [get_nets [list {udp_axi/read_addr[0]} {udp_axi/read_addr[1]} {udp_axi/read_addr[2]} {udp_axi/read_addr[3]} {udp_axi/read_addr[4]} {udp_axi/read_addr[5]} {udp_axi/read_addr[6]} {udp_axi/read_addr[7]} {udp_axi/read_addr[8]} {udp_axi/read_addr[9]} {udp_axi/read_addr[10]} {udp_axi/read_addr[11]} {udp_axi/read_addr[12]} {udp_axi/read_addr[13]} {udp_axi/read_addr[14]} {udp_axi/read_addr[15]} {udp_axi/read_addr[16]} {udp_axi/read_addr[17]} {udp_axi/read_addr[18]} {udp_axi/read_addr[19]} {udp_axi/read_addr[20]} {udp_axi/read_addr[21]} {udp_axi/read_addr[22]} {udp_axi/read_addr[23]} {udp_axi/read_addr[24]} {udp_axi/read_addr[25]} {udp_axi/read_addr[26]} {udp_axi/read_addr[27]} {udp_axi/read_addr[28]} {udp_axi/read_addr[29]} {udp_axi/read_addr[30]} {udp_axi/read_addr[31]}]]
connect_debug_port u_ila_1/probe4 [get_nets [list {udp_axi/w_data[0]} {udp_axi/w_data[1]} {udp_axi/w_data[2]} {udp_axi/w_data[3]} {udp_axi/w_data[4]} {udp_axi/w_data[5]} {udp_axi/w_data[6]} {udp_axi/w_data[7]} {udp_axi/w_data[8]} {udp_axi/w_data[9]} {udp_axi/w_data[10]} {udp_axi/w_data[11]} {udp_axi/w_data[12]} {udp_axi/w_data[13]} {udp_axi/w_data[14]} {udp_axi/w_data[15]} {udp_axi/w_data[16]} {udp_axi/w_data[17]} {udp_axi/w_data[18]} {udp_axi/w_data[19]} {udp_axi/w_data[20]} {udp_axi/w_data[21]} {udp_axi/w_data[22]} {udp_axi/w_data[23]} {udp_axi/w_data[24]} {udp_axi/w_data[25]} {udp_axi/w_data[26]} {udp_axi/w_data[27]} {udp_axi/w_data[28]} {udp_axi/w_data[29]} {udp_axi/w_data[30]} {udp_axi/w_data[31]}]]
connect_debug_port u_ila_1/probe5 [get_nets [list {udp_axi/state[0]} {udp_axi/state[1]} {udp_axi/state[2]} {udp_axi/state[3]}]]
connect_debug_port u_ila_1/probe6 [get_nets [list udp_axi/ctrl_we]]
connect_debug_port u_ila_1/probe7 [get_nets [list udp_axi/data_we]]
connect_debug_port u_ila_1/probe9 [get_nets [list udp_axi/r_enable]]
connect_debug_port u_ila_1/probe10 [get_nets [list udp_axi/w_enable]]
connect_debug_port u_ila_1/probe11 [get_nets [list udp_axi/w_req]]


set_property OFFCHIP_TERM NONE [get_ports GEPHY_RST_N]
set_property OFFCHIP_TERM NONE [get_ports GEPHY_TCK]
set_property OFFCHIP_TERM NONE [get_ports GEPHY_TXEN_ER]
set_property OFFCHIP_TERM NONE [get_ports LED0]
set_property OFFCHIP_TERM NONE [get_ports LED1]
set_property OFFCHIP_TERM NONE [get_ports LED2]
set_property OFFCHIP_TERM NONE [get_ports GEPHY_TD[3]]
set_property OFFCHIP_TERM NONE [get_ports GEPHY_TD[2]]
set_property OFFCHIP_TERM NONE [get_ports GEPHY_TD[1]]
set_property OFFCHIP_TERM NONE [get_ports GEPHY_TD[0]]
