set_property -dict {PACKAGE_PIN AA14 IOSTANDARD LVCMOS33} [get_ports {GEPHY_RD[3]}]
set_property -dict {PACKAGE_PIN Y13  IOSTANDARD LVCMOS33} [get_ports {GEPHY_RD[2]}]
set_property -dict {PACKAGE_PIN AB15 IOSTANDARD LVCMOS33} [get_ports {GEPHY_RD[1]}]
set_property -dict {PACKAGE_PIN AA15 IOSTANDARD LVCMOS33} [get_ports {GEPHY_RD[0]}]
set_property -dict {PACKAGE_PIN AB17 IOSTANDARD LVCMOS33} [get_ports {GEPHY_TD[3]}]
set_property -dict {PACKAGE_PIN AB16 IOSTANDARD LVCMOS33} [get_ports {GEPHY_TD[2]}]
set_property -dict {PACKAGE_PIN AA16 IOSTANDARD LVCMOS33} [get_ports {GEPHY_TD[1]}]
set_property -dict {PACKAGE_PIN Y16  IOSTANDARD LVCMOS33} [get_ports {GEPHY_TD[0]}]
set_property -dict {PACKAGE_PIN W11  IOSTANDARD LVCMOS33} [get_ports GEPHY_MAC_CLK]
set_property -dict {PACKAGE_PIN T16  IOSTANDARD LVCMOS33} [get_ports GEPHY_PMEB]
set_property -dict {PACKAGE_PIN Y11  IOSTANDARD LVCMOS33} [get_ports GEPHY_RCK]
set_property -dict {PACKAGE_PIN U16  IOSTANDARD LVCMOS33} [get_ports GEPHY_RST_N]
set_property -dict {PACKAGE_PIN AA9  IOSTANDARD LVCMOS33} [get_ports GEPHY_RXDV_ER]
set_property -dict {PACKAGE_PIN AB13 IOSTANDARD LVCMOS33} [get_ports GEPHY_TCK]
set_property -dict {PACKAGE_PIN AA13 IOSTANDARD LVCMOS33} [get_ports GEPHY_TXEN_ER]
set_property -dict {PACKAGE_PIN E21  IOSTANDARD LVCMOS33} [get_ports LED0]
set_property -dict {PACKAGE_PIN D21  IOSTANDARD LVCMOS33} [get_ports LED1]
set_property -dict {PACKAGE_PIN G22  IOSTANDARD LVCMOS33} [get_ports LED2]
set_property -dict {PACKAGE_PIN H4   IOSTANDARD LVDS_25}  [get_ports sys_clk_p]
set_property -dict {PACKAGE_PIN G4   IOSTANDARD LVDS_25}  [get_ports sys_clk_n]
set_property -dict {PACKAGE_PIN D19  IOSTANDARD LVCMOS33} [get_ports sys_rst_n]

set_property -dict {PACKAGE_PIN C14  IOSTANDARD LVCMOS33} [get_ports GPIO00]
set_property -dict {PACKAGE_PIN C15  IOSTANDARD LVCMOS33} [get_ports GPIO01]
set_property -dict {PACKAGE_PIN D14  IOSTANDARD LVCMOS33} [get_ports GPIO02]
set_property -dict {PACKAGE_PIN D15  IOSTANDARD LVCMOS33} [get_ports GPIO03]
set_property -dict {PACKAGE_PIN B15  IOSTANDARD LVCMOS33} [get_ports GPIO04]
set_property -dict {PACKAGE_PIN B16  IOSTANDARD LVCMOS33} [get_ports GPIO05]
set_property -dict {PACKAGE_PIN C13  IOSTANDARD LVCMOS33} [get_ports GPIO06]
set_property -dict {PACKAGE_PIN B13  IOSTANDARD LVCMOS33} [get_ports GPIO07]
set_property -dict {PACKAGE_PIN A15  IOSTANDARD LVCMOS33} [get_ports GPIO10]
set_property -dict {PACKAGE_PIN A16  IOSTANDARD LVCMOS33} [get_ports GPIO11]
set_property -dict {PACKAGE_PIN A13  IOSTANDARD LVCMOS33} [get_ports GPIO12]
set_property -dict {PACKAGE_PIN A14  IOSTANDARD LVCMOS33} [get_ports GPIO13]
set_property -dict {PACKAGE_PIN B17  IOSTANDARD LVCMOS33} [get_ports GPIO14]
set_property -dict {PACKAGE_PIN B18  IOSTANDARD LVCMOS33} [get_ports GPIO15]
set_property -dict {PACKAGE_PIN C18  IOSTANDARD LVCMOS33} [get_ports GPIO20]
set_property -dict {PACKAGE_PIN C19  IOSTANDARD LVCMOS33} [get_ports GPIO21]
set_property -dict {PACKAGE_PIN B20  IOSTANDARD LVCMOS33} [get_ports GPIO22]
set_property -dict {PACKAGE_PIN A20  IOSTANDARD LVCMOS33} [get_ports GPIO23]
set_property -dict {PACKAGE_PIN A18  IOSTANDARD LVCMOS33} [get_ports GPIO24]
set_property -dict {PACKAGE_PIN A19  IOSTANDARD LVCMOS33} [get_ports GPIO25]
set_property -dict {PACKAGE_PIN D20  IOSTANDARD LVCMOS33} [get_ports GPIO26]
set_property -dict {PACKAGE_PIN C20  IOSTANDARD LVCMOS33} [get_ports GPIO27]
set_property -dict {PACKAGE_PIN C22  IOSTANDARD LVCMOS33} [get_ports GPIO30]
set_property -dict {PACKAGE_PIN B22  IOSTANDARD LVCMOS33} [get_ports GPIO31]
set_property -dict {PACKAGE_PIN B21  IOSTANDARD LVCMOS33} [get_ports GPIO32]
set_property -dict {PACKAGE_PIN A21  IOSTANDARD LVCMOS33} [get_ports GPIO33]
set_property -dict {PACKAGE_PIN E22  IOSTANDARD LVCMOS33} [get_ports GPIO34]
set_property -dict {PACKAGE_PIN D22  IOSTANDARD LVCMOS33} [get_ports GPIO35]

set_property -dict {PACKAGE_PIN G17  IOSTANDARD LVCMOS33} [get_ports GPIO40]
set_property -dict {PACKAGE_PIN G18  IOSTANDARD LVCMOS33} [get_ports GPIO41]
set_property -dict {PACKAGE_PIN H17  IOSTANDARD LVCMOS33} [get_ports GPIO42]
set_property -dict {PACKAGE_PIN H18  IOSTANDARD LVCMOS33} [get_ports GPIO43]
set_property -dict {PACKAGE_PIN J22  IOSTANDARD LVCMOS33} [get_ports GPIO44]
set_property -dict {PACKAGE_PIN H22  IOSTANDARD LVCMOS33} [get_ports GPIO45]
set_property -dict {PACKAGE_PIN H20  IOSTANDARD LVCMOS33} [get_ports GPIO46]
set_property -dict {PACKAGE_PIN G20  IOSTANDARD LVCMOS33} [get_ports GPIO47]
set_property -dict {PACKAGE_PIN K21  IOSTANDARD LVCMOS33} [get_ports GPIO50]
set_property -dict {PACKAGE_PIN K22  IOSTANDARD LVCMOS33} [get_ports GPIO51]
set_property -dict {PACKAGE_PIN M21  IOSTANDARD LVCMOS33} [get_ports GPIO52]
set_property -dict {PACKAGE_PIN L21  IOSTANDARD LVCMOS33} [get_ports GPIO53]
set_property -dict {PACKAGE_PIN J20  IOSTANDARD LVCMOS33} [get_ports GPIO54]
set_property -dict {PACKAGE_PIN J21  IOSTANDARD LVCMOS33} [get_ports GPIO55]
set_property -dict {PACKAGE_PIN K18  IOSTANDARD LVCMOS33} [get_ports GPIO60]
set_property -dict {PACKAGE_PIN K19  IOSTANDARD LVCMOS33} [get_ports GPIO61]
set_property -dict {PACKAGE_PIN L19  IOSTANDARD LVCMOS33} [get_ports GPIO62]
set_property -dict {PACKAGE_PIN L20  IOSTANDARD LVCMOS33} [get_ports GPIO63]
set_property -dict {PACKAGE_PIN N22  IOSTANDARD LVCMOS33} [get_ports GPIO64]
set_property -dict {PACKAGE_PIN M22  IOSTANDARD LVCMOS33} [get_ports GPIO65]
set_property -dict {PACKAGE_PIN M18  IOSTANDARD LVCMOS33} [get_ports GPIO66]
set_property -dict {PACKAGE_PIN L18  IOSTANDARD LVCMOS33} [get_ports GPIO67]
set_property -dict {PACKAGE_PIN N18  IOSTANDARD LVCMOS33} [get_ports GPIO70]
set_property -dict {PACKAGE_PIN N19  IOSTANDARD LVCMOS33} [get_ports GPIO71]
set_property -dict {PACKAGE_PIN N20  IOSTANDARD LVCMOS33} [get_ports GPIO72]
set_property -dict {PACKAGE_PIN M20  IOSTANDARD LVCMOS33} [get_ports GPIO73]
set_property -dict {PACKAGE_PIN K17  IOSTANDARD LVCMOS33} [get_ports GPIO74]
set_property -dict {PACKAGE_PIN J17  IOSTANDARD LVCMOS33} [get_ports GPIO75]

set_property -dict {PACKAGE_PIN U22  IOSTANDARD LVCMOS33} [get_ports HDMI0_D0_P]
set_property -dict {PACKAGE_PIN V22  IOSTANDARD LVCMOS33} [get_ports HDMI0_D0_N]
set_property -dict {PACKAGE_PIN T21  IOSTANDARD LVCMOS33} [get_ports HDMI0_D1_P]
set_property -dict {PACKAGE_PIN U21  IOSTANDARD LVCMOS33} [get_ports HDMI0_D1_N]
set_property -dict {PACKAGE_PIN P19  IOSTANDARD LVCMOS33} [get_ports HDMI0_D2_P]
set_property -dict {PACKAGE_PIN R19  IOSTANDARD LVCMOS33} [get_ports HDMI0_D2_N]
set_property -dict {PACKAGE_PIN W21  IOSTANDARD LVCMOS33} [get_ports HDMI0_SCL]
set_property -dict {PACKAGE_PIN W22  IOSTANDARD LVCMOS33} [get_ports HDMI0_SDA]
set_property -dict {PACKAGE_PIN U20  IOSTANDARD LVCMOS33} [get_ports HDMI0_CLK_P]
set_property -dict {PACKAGE_PIN V20  IOSTANDARD LVCMOS33} [get_ports HDMI0_CLK_N]

set_property -dict {PACKAGE_PIN Y18  IOSTANDARD LVCMOS33} [get_ports HDMI1_D0_P]
set_property -dict {PACKAGE_PIN Y19  IOSTANDARD LVCMOS33} [get_ports HDMI1_D0_N]
set_property -dict {PACKAGE_PIN V18  IOSTANDARD LVCMOS33} [get_ports HDMI1_D1_P]
set_property -dict {PACKAGE_PIN V19  IOSTANDARD LVCMOS33} [get_ports HDMI1_D1_N]
set_property -dict {PACKAGE_PIN AA19 IOSTANDARD LVCMOS33} [get_ports HDMI1_D2_P]
set_property -dict {PACKAGE_PIN AB20 IOSTANDARD LVCMOS33} [get_ports HDMI1_D2_N]
set_property -dict {PACKAGE_PIN AA20 IOSTANDARD LVCMOS33} [get_ports HDMI1_SCL]
set_property -dict {PACKAGE_PIN AA21 IOSTANDARD LVCMOS33} [get_ports HDMI1_SDA]
set_property -dict {PACKAGE_PIN W19  IOSTANDARD LVCMOS33} [get_ports HDMI1_CLK_P]
set_property -dict {PACKAGE_PIN W20  IOSTANDARD LVCMOS33} [get_ports HDMI1_CLK_N]

set_property -dict {PACKAGE_PIN R18  IOSTANDARD LVCMOS33} [get_ports {PMOD[0]}]
set_property -dict {PACKAGE_PIN T18  IOSTANDARD LVCMOS33} [get_ports {PMOD[1]}]
set_property -dict {PACKAGE_PIN N17  IOSTANDARD LVCMOS33} [get_ports {PMOD[2]}]
set_property -dict {PACKAGE_PIN P17  IOSTANDARD LVCMOS33} [get_ports {PMOD[3]}]

set_property -dict {PACKAGE_PIN AA11 IOSTANDARD LVCMOS33} [get_ports GEPHY_INT_N]
set_property -dict {PACKAGE_PIN AA10 IOSTANDARD LVCMOS33} [get_ports GEPHY_MDC]
set_property -dict {PACKAGE_PIN AB10 IOSTANDARD LVCMOS33} [get_ports GEPHY_MDIO]

#create_clock -period 5.000 -name sysclk [get_ports sys_clk_p]
#create_clock -period 8.000 -name macclk -waveform {0.000 4.000} [get_ports GEPHY_MAC_CLK]
create_clock -period 8.000 -name rgmii_rxclk -waveform {2.200 6.200} [get_ports GEPHY_RCK]

set_false_path -from [get_clocks rgmii_rxclk] -to [get_clocks -of_objects [get_pins clk_wiz_1_i/inst/mmcm_adv_inst/CLKOUT1]]
set_false_path -from [get_clocks -of_objects [get_pins clk_wiz_1_i/inst/mmcm_adv_inst/CLKOUT1]] -to [get_clocks rgmii_rxclk]

## 90-degree shift from RCK
set_input_delay -clock [get_clocks rgmii_rxclk] -clock_fall -min -add_delay 1.000 [get_ports {GEPHY_RD[*]}]
set_input_delay -clock [get_clocks rgmii_rxclk] -clock_fall -max -add_delay 3.000 [get_ports {GEPHY_RD[*]}]
set_input_delay -clock [get_clocks rgmii_rxclk] -min -add_delay 1.000 [get_ports {GEPHY_RD[*]}]
set_input_delay -clock [get_clocks rgmii_rxclk] -max -add_delay 3.000 [get_ports {GEPHY_RD[*]}]
set_input_delay -clock [get_clocks rgmii_rxclk] -clock_fall -min -add_delay 1.000 [get_ports GEPHY_RXDV_ER]
set_input_delay -clock [get_clocks rgmii_rxclk] -clock_fall -max -add_delay 3.000 [get_ports GEPHY_RXDV_ER]
set_input_delay -clock [get_clocks rgmii_rxclk] -min -add_delay 1.000 [get_ports GEPHY_RXDV_ER]
set_input_delay -clock [get_clocks rgmii_rxclk] -max -add_delay 3.000 [get_ports GEPHY_RXDV_ER]

## 90-degree shift from TCK
create_generated_clock -name GEPHY_TCK -source [get_pins u_e7udpip/u_e7udpip/u_ether/u_gmiitx/miitxregs_a7.txclk_ddr/C] -divide_by 1 [get_ports GEPHY_TCK]
set_output_delay -clock [get_clocks GEPHY_TCK] -clock_fall -min -add_delay 1.000 [get_ports {GEPHY_TD[*]}]
set_output_delay -clock [get_clocks GEPHY_TCK] -clock_fall -max -add_delay 3.000 [get_ports {GEPHY_TD[*]}]
set_output_delay -clock [get_clocks GEPHY_TCK] -max -add_delay 3.000 [get_ports {GEPHY_TD[*]}]
set_output_delay -clock [get_clocks GEPHY_TCK] -max -add_delay 3.000 [get_ports {GEPHY_TD[*]}]

set_output_delay -clock [get_clocks GEPHY_TCK] -clock_fall -min -add_delay 1.000 [get_ports GEPHY_TXEN_ER]
set_output_delay -clock [get_clocks GEPHY_TCK] -clock_fall -max -add_delay 3.000 [get_ports GEPHY_TXEN_ER]
set_output_delay -clock [get_clocks GEPHY_TCK] -min -add_delay 1.000 [get_ports GEPHY_TXEN_ER]
set_output_delay -clock [get_clocks GEPHY_TCK] -max -add_delay 3.000 [get_ports GEPHY_TXEN_ER]

create_pblock pblock_u_e7udpip
add_cells_to_pblock [get_pblocks pblock_u_e7udpip] [get_cells -quiet [list u_e7udpip]]
resize_pblock [get_pblocks pblock_u_e7udpip] -add {CLOCKREGION_X0Y1:CLOCKREGION_X0Y1}

set_property OFFCHIP_TERM NONE [get_ports GEPHY_RST_N]
set_property OFFCHIP_TERM NONE [get_ports GEPHY_TCK]
set_property OFFCHIP_TERM NONE [get_ports GEPHY_TD[0]]
set_property OFFCHIP_TERM NONE [get_ports GEPHY_TD[1]]
set_property OFFCHIP_TERM NONE [get_ports GEPHY_TD[2]]
set_property OFFCHIP_TERM NONE [get_ports GEPHY_TD[3]]
set_property OFFCHIP_TERM NONE [get_ports GEPHY_TXEN_ER]
set_property OFFCHIP_TERM NONE [get_ports LED0]
set_property OFFCHIP_TERM NONE [get_ports LED1]
set_property OFFCHIP_TERM NONE [get_ports LED2]

set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
